[build-system]
requires = ["linktools-setup @ git+https://github.com/linktools-toolkit/linktools-setup.git@ac8fa0749f14eb3b57b5f359bc25773f99a7b4fa"]
build-backend = "linktools_setup.build_meta"

[project]
name = "linktools-ai"
description = "linktools toolkit"
requires-python = ">=3.10"
authors = [{name = "Hu Ji", email = "669898595@qq.com"}]
dynamic = ["version", "dependencies", "optional-dependencies", "scripts", "entry-points"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "Apache-2.0"

[project.urls]
Homepage = "https://github.com/ice-black-tea/linktools"
Repository = "https://github.com/ice-black-tea/linktools.git"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["linktools*"]

[tool.setuptools.package-data]
linktools = ["**/assets/**", "**/*.json", "**/*.md"]
