#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Frozen MESSAGE_WIRE_V1 schema artifacts."""

MESSAGE_WIRE_VERSION = 1
V1_BASELINE_PYTHON = "3.12"
V1_BASELINE_PYDANTIC_AI = "2.27.0"
V1_BASELINE_PYDANTIC = "2.12.0"

V1_SERIALIZATION_SCHEMA_JSON: str = (
    '{"$defs":{"AudioUrl":{"additionalProperties":false,"description":"A URL to an audio file.","properti'
    'es":{"force_download":{"anyOf":[{"type":"boolean"},{"const":"allow-local","type":"string"}],"default'
    '":false,"title":"Force Download"},"identifier":{"description":"The identifier of the file, such as a'
    " unique ID.\\n\\nThis identifier can be provided to the model in a message to allow it to refer to thi"
    "s file in a tool call argument,\\nand the tool can look up the file in question by iterating over the"
    " message history and finding the matching `FileUrl`.\\n\\nThis identifier is only automatically passed"
    " to the model when the `FileUrl` is returned by a tool.\\nIf you're passing the `FileUrl` as a user m"
    "essage, it's up to you to include a separate text part with the identifier,\\ne.g. \\\"This is file <id"
    "entifier>:\\\" preceding the `FileUrl`.\\n\\nIt's also included in inline-text delimiters for providers "
    'that require inlining text documents, so the model can\\ndistinguish multiple files.","readOnly":true'
    ',"title":"Identifier","type":"string"},"kind":{"const":"audio-url","default":"audio-url","title":"Ki'
    'nd","type":"string"},"media_type":{"description":"Return the media type of the file, based on the UR'
    'L or the provided `media_type`.","readOnly":true,"title":"Media Type","type":"string"},"url":{"title'
    '":"Url","type":"string"},"vendor_metadata":{"anyOf":[{"additionalProperties":true,"type":"object"},{'
    '"type":"null"}],"default":null,"title":"Vendor Metadata"}},"required":["url","media_type","identifie'
    'r"],"title":"AudioUrl","type":"object"},"BinaryContent":{"additionalProperties":false,"description":'
    '"Binary content, e.g. an audio or image file.","properties":{"data":{"format":"base64url","title":"D'
    'ata","type":"string"},"identifier":{"description":"Identifier for the binary content, such as a uniq'
    "ue ID.\\n\\nThis identifier can be provided to the model in a message to allow it to refer to this fil"
    "e in a tool call argument,\\nand the tool can look up the file in question by iterating over the mess"
    "age history and finding the matching `BinaryContent`.\\n\\nThis identifier is only automatically passe"
    "d to the model when the `BinaryContent` is returned by a tool.\\nIf you're passing the `BinaryContent"
    "` as a user message, it's up to you to include a separate text part with the identifier,\\ne.g. \\\"Thi"
    "s is file <identifier>:\\\" preceding the `BinaryContent`.\\n\\nIt's also included in inline-text delimi"
    "ters for providers that require inlining text documents, so the model can\\ndistinguish multiple file"
    's.","readOnly":true,"title":"Identifier","type":"string"},"kind":{"const":"binary","default":"binary'
    '","title":"Kind","type":"string"},"media_type":{"anyOf":[{"enum":["audio/wav","audio/mpeg","audio/og'
    'g","audio/flac","audio/aiff","audio/aac"],"type":"string"},{"enum":["image/jpeg","image/png","image/'
    'gif","image/webp"],"type":"string"},{"enum":["application/pdf","text/plain","text/csv","application/'
    'vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officed'
    'ocument.spreadsheetml.sheet","text/html","text/markdown","application/msword","application/vnd.ms-ex'
    'cel"],"type":"string"},{"type":"string"}],"title":"Media Type"},"vendor_metadata":{"anyOf":[{"additi'
    'onalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Vendor Metadata"}},"r'
    'equired":["data","media_type","identifier"],"title":"BinaryContent","type":"object"},"CachePoint":{"'
    'additionalProperties":false,"properties":{"kind":{"const":"cache-point","default":"cache-point","tit'
    'le":"Kind","type":"string"},"ttl":{"default":"5m","enum":["5m","1h"],"title":"Ttl","type":"string"}}'
    ',"title":"CachePoint","type":"object"},"CompactionPart":{"additionalProperties":false,"properties":{'
    '"content":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Content"},"id":{"anyO'
    'f":[{"type":"string"},{"type":"null"}],"default":null,"title":"Id"},"part_kind":{"const":"compaction'
    '","default":"compaction","title":"Part Kind","type":"string"},"provider_details":{"anyOf":[{"additio'
    'nalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Provider Details"},"pr'
    'ovider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Name"}},"'
    'title":"CompactionPart","type":"object"},"DocumentUrl":{"additionalProperties":false,"description":"'
    'The URL of the document.","properties":{"force_download":{"anyOf":[{"type":"boolean"},{"const":"allo'
    'w-local","type":"string"}],"default":false,"title":"Force Download"},"identifier":{"description":"Th'
    "e identifier of the file, such as a unique ID.\\n\\nThis identifier can be provided to the model in a "
    "message to allow it to refer to this file in a tool call argument,\\nand the tool can look up the fil"
    "e in question by iterating over the message history and finding the matching `FileUrl`.\\n\\nThis iden"
    "tifier is only automatically passed to the model when the `FileUrl` is returned by a tool.\\nIf you'r"
    "e passing the `FileUrl` as a user message, it's up to you to include a separate text part with the i"
    'dentifier,\\ne.g. \\"This is file <identifier>:\\" preceding the `FileUrl`.\\n\\nIt\'s also included in in'
    "line-text delimiters for providers that require inlining text documents, so the model can\\ndistingui"
    'sh multiple files.","readOnly":true,"title":"Identifier","type":"string"},"kind":{"const":"document-'
    'url","default":"document-url","title":"Kind","type":"string"},"media_type":{"description":"Return th'
    'e media type of the file, based on the URL or the provided `media_type`.","readOnly":true,"title":"M'
    'edia Type","type":"string"},"url":{"title":"Url","type":"string"},"vendor_metadata":{"anyOf":[{"addi'
    'tionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Vendor Metadata"}},'
    '"required":["url","media_type","identifier"],"title":"DocumentUrl","type":"object"},"ErrorDetails":{'
    '"additionalProperties":false,"properties":{"ctx":{"additionalProperties":true,"title":"Ctx","type":"'
    'object"},"input":{"title":"Input"},"loc":{"items":{"anyOf":[{"type":"integer"},{"type":"string"}]},"'
    'title":"Loc","type":"array"},"msg":{"title":"Msg","type":"string"},"type":{"title":"Type","type":"st'
    'ring"},"url":{"title":"Url","type":"string"}},"required":["type","loc","msg","input"],"title":"Error'
    'Details","type":"object"},"FilePart":{"additionalProperties":false,"properties":{"content":{"$ref":"'
    '#/$defs/BinaryContent"},"id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Id'
    '"},"part_kind":{"const":"file","default":"file","title":"Part Kind","type":"string"},"provider_detai'
    'ls":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":'
    '"Provider Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"tit'
    'le":"Provider Name"}},"required":["content"],"title":"FilePart","type":"object"},"ImageUrl":{"additi'
    'onalProperties":false,"description":"A URL to an image.","properties":{"force_download":{"anyOf":[{"'
    'type":"boolean"},{"const":"allow-local","type":"string"}],"default":false,"title":"Force Download"},'
    '"identifier":{"description":"The identifier of the file, such as a unique ID.\\n\\nThis identifier can'
    " be provided to the model in a message to allow it to refer to this file in a tool call argument,\\na"
    "nd the tool can look up the file in question by iterating over the message history and finding the m"
    "atching `FileUrl`.\\n\\nThis identifier is only automatically passed to the model when the `FileUrl` i"
    "s returned by a tool.\\nIf you're passing the `FileUrl` as a user message, it's up to you to include "
    'a separate text part with the identifier,\\ne.g. \\"This is file <identifier>:\\" preceding the `FileUr'
    "l`.\\n\\nIt's also included in inline-text delimiters for providers that require inlining text documen"
    'ts, so the model can\\ndistinguish multiple files.","readOnly":true,"title":"Identifier","type":"stri'
    'ng"},"kind":{"const":"image-url","default":"image-url","title":"Kind","type":"string"},"media_type":'
    '{"description":"Return the media type of the file, based on the URL or the provided `media_type`.","'
    'readOnly":true,"title":"Media Type","type":"string"},"url":{"title":"Url","type":"string"},"vendor_m'
    'etadata":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"ti'
    'tle":"Vendor Metadata"}},"required":["url","media_type","identifier"],"title":"ImageUrl","type":"obj'
    'ect"},"LoadCapabilityArgs":{"additionalProperties":false,"description":"Typed arguments for a `load_'
    'capability` tool call.","properties":{"id":{"description":"The id of the capability to load.","title'
    '":"Id","type":"string"}},"required":["id"],"title":"LoadCapabilityArgs","type":"object"},"LoadCapabi'
    'lityCallPart":{"additionalProperties":false,"properties":{"args":{"anyOf":[{"type":"string"},{"$ref"'
    ':"#/$defs/LoadCapabilityArgs"},{"type":"null"}],"default":null,"title":"Args"},"id":{"anyOf":[{"type'
    '":"string"},{"type":"null"}],"default":null,"title":"Id"},"part_kind":{"const":"tool-call","default"'
    ':"tool-call","title":"Part Kind","type":"string"},"provider_details":{"anyOf":[{"additionalPropertie'
    's":true,"type":"object"},{"type":"null"}],"default":null,"title":"Provider Details"},"provider_name"'
    ':{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Name"},"tool_call_id"'
    ':{"title":"Tool Call Id","type":"string"},"tool_kind":{"const":"capability-load","default":"capabili'
    'ty-load","title":"Tool Kind","type":"string"},"tool_name":{"const":"load_capability","default":"load'
    '_capability","title":"Tool Name","type":"string"}},"title":"LoadCapabilityCallPart","type":"object"}'
    ',"LoadCapabilityReturn":{"additionalProperties":false,"description":"Typed return value for the `loa'
    'd_capability` tool.","properties":{"instructions":{"title":"Instructions","type":"string"}},"title":'
    '"LoadCapabilityReturn","type":"object"},"LoadCapabilityReturnPart":{"additionalProperties":false,"pr'
    'operties":{"content":{"$ref":"#/$defs/LoadCapabilityReturn"},"metadata":{"default":null,"title":"Met'
    'adata"},"outcome":{"default":"success","enum":["success","failed","denied","interrupted"],"title":"O'
    'utcome","type":"string"},"part_kind":{"const":"tool-return","default":"tool-return","title":"Part Ki'
    'nd","type":"string"},"timestamp":{"format":"date-time","title":"Timestamp","type":"string"},"tool_ca'
    'll_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"const":"capability-load","default":"ca'
    'pability-load","title":"Tool Kind","type":"string"},"tool_name":{"const":"load_capability","default"'
    ':"load_capability","title":"Tool Name","type":"string"}},"required":["content"],"title":"LoadCapabil'
    'ityReturnPart","type":"object"},"ModelRequest":{"additionalProperties":false,"properties":{"conversa'
    'tion_id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Conversation Id"},"ins'
    'tructions":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Instructions"},"kind'
    '":{"const":"request","default":"request","title":"Kind","type":"string"},"metadata":{"anyOf":[{"addi'
    'tionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Metadata"},"parts":'
    '{"items":{"oneOf":[{"$ref":"#/$defs/SystemPromptPart"},{"$ref":"#/$defs/UserPromptPart"},{"$ref":"#/'
    '$defs/ToolSearchReturnPart"},{"$ref":"#/$defs/LoadCapabilityReturnPart"},{"$ref":"#/$defs/ToolReturn'
    'Part"},{"$ref":"#/$defs/RetryPromptPart"},{"$ref":"#/$defs/ToolAvailabilityDeltaPart"}]},"title":"Pa'
    'rts","type":"array"},"run_id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"R'
    'un Id"},"state":{"default":"complete","enum":["complete","interrupted"],"title":"State","type":"stri'
    'ng"},"timestamp":{"anyOf":[{"format":"date-time","type":"string"},{"type":"null"}],"default":null,"t'
    'itle":"Timestamp"}},"required":["parts"],"title":"ModelRequest","type":"object"},"ModelResponse":{"a'
    'dditionalProperties":false,"properties":{"conversation_id":{"anyOf":[{"type":"string"},{"type":"null'
    '"}],"default":null,"title":"Conversation Id"},"finish_reason":{"anyOf":[{"enum":["stop","length","co'
    'ntent_filter","tool_call","error"],"type":"string"},{"type":"null"}],"default":null,"title":"Finish '
    'Reason"},"kind":{"const":"response","default":"response","title":"Kind","type":"string"},"metadata":'
    '{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Met'
    'adata"},"model_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Model Name'
    '"},"parts":{"items":{"oneOf":[{"$ref":"#/$defs/TextPart"},{"$ref":"#/$defs/ToolSearchCallPart"},{"$r'
    'ef":"#/$defs/LoadCapabilityCallPart"},{"$ref":"#/$defs/ToolCallPart"},{"$ref":"#/$defs/NativeToolSea'
    'rchCallPart"},{"$ref":"#/$defs/NativeToolCallPart"},{"$ref":"#/$defs/NativeToolSearchReturnPart"},{"'
    '$ref":"#/$defs/NativeToolReturnPart"},{"$ref":"#/$defs/ThinkingPart"},{"$ref":"#/$defs/CompactionPar'
    't"},{"$ref":"#/$defs/FilePart"}]},"title":"Parts","type":"array"},"provider_details":{"anyOf":[{"add'
    'itionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Provider Details"}'
    ',"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Name"'
    '},"provider_response_id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provid'
    'er Response Id"},"provider_url":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":'
    '"Provider Url"},"run_id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Run Id'
    '"},"state":{"default":"complete","enum":["complete","incomplete","suspended","interrupted"],"title":'
    '"State","type":"string"},"timestamp":{"format":"date-time","title":"Timestamp","type":"string"},"usa'
    'ge":{"$ref":"#/$defs/RequestUsage"}},"required":["parts"],"title":"ModelResponse","type":"object"},"'
    'NativeToolCallPart":{"additionalProperties":false,"properties":{"args":{"anyOf":[{"type":"string"},{'
    '"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Args"},"id":{"'
    'anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Id"},"part_kind":{"const":"builti'
    'n-tool-call","default":"builtin-tool-call","title":"Part Kind","type":"string"},"provider_details":{'
    '"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Prov'
    'ider Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"'
    'Provider Name"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"anyOf":[{"enum'
    '":["tool-search","capability-load"],"type":"string"},{"type":"null"}],"default":null,"title":"Tool K'
    'ind"},"tool_name":{"title":"Tool Name","type":"string"}},"required":["tool_name"],"title":"NativeToo'
    'lCallPart","type":"object"},"NativeToolReturnPart":{"additionalProperties":false,"properties":{"cont'
    'ent":{"$ref":"#/$defs/ToolReturnContent"},"metadata":{"default":null,"title":"Metadata"},"outcome":{'
    '"default":"success","enum":["success","failed","denied","interrupted"],"title":"Outcome","type":"str'
    'ing"},"part_kind":{"const":"builtin-tool-return","default":"builtin-tool-return","title":"Part Kind"'
    ',"type":"string"},"provider_details":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type"'
    ':"null"}],"default":null,"title":"Provider Details"},"provider_name":{"anyOf":[{"type":"string"},{"t'
    'ype":"null"}],"default":null,"title":"Provider Name"},"timestamp":{"format":"date-time","title":"Tim'
    'estamp","type":"string"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"anyOf'
    '":[{"enum":["tool-search","capability-load"],"type":"string"},{"type":"null"}],"default":null,"title'
    '":"Tool Kind"},"tool_name":{"title":"Tool Name","type":"string"}},"required":["tool_name","content"]'
    ',"title":"NativeToolReturnPart","type":"object"},"NativeToolSearchCallPart":{"additionalProperties":'
    'false,"properties":{"args":{"anyOf":[{"type":"string"},{"$ref":"#/$defs/ToolSearchArgs"},{"type":"nu'
    'll"}],"default":null,"title":"Args"},"id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":nul'
    'l,"title":"Id"},"part_kind":{"const":"builtin-tool-call","default":"builtin-tool-call","title":"Part'
    ' Kind","type":"string"},"provider_details":{"anyOf":[{"additionalProperties":true,"type":"object"},{'
    '"type":"null"}],"default":null,"title":"Provider Details"},"provider_name":{"anyOf":[{"type":"string'
    '"},{"type":"null"}],"default":null,"title":"Provider Name"},"tool_call_id":{"title":"Tool Call Id","'
    'type":"string"},"tool_kind":{"const":"tool-search","default":"tool-search","title":"Tool Kind","type'
    '":"string"},"tool_name":{"const":"tool_search","default":"tool_search","title":"Tool Name","type":"s'
    'tring"}},"title":"NativeToolSearchCallPart","type":"object"},"NativeToolSearchReturnPart":{"addition'
    'alProperties":false,"properties":{"content":{"$ref":"#/$defs/ToolSearchReturnContent"},"metadata":{"'
    'default":null,"title":"Metadata"},"outcome":{"default":"success","enum":["success","failed","denied"'
    ',"interrupted"],"title":"Outcome","type":"string"},"part_kind":{"const":"builtin-tool-return","defau'
    'lt":"builtin-tool-return","title":"Part Kind","type":"string"},"provider_details":{"anyOf":[{"additi'
    'onalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Provider Details"},"p'
    'rovider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Name"},"'
    'timestamp":{"format":"date-time","title":"Timestamp","type":"string"},"tool_call_id":{"title":"Tool '
    'Call Id","type":"string"},"tool_kind":{"const":"tool-search","default":"tool-search","title":"Tool K'
    'ind","type":"string"},"tool_name":{"const":"tool_search","default":"tool_search","title":"Tool Name"'
    ',"type":"string"}},"required":["content"],"title":"NativeToolSearchReturnPart","type":"object"},"Req'
    'uestUsage":{"additionalProperties":false,"properties":{"cache_audio_read_tokens":{"default":0,"title'
    '":"Cache Audio Read Tokens","type":"integer"},"cache_read_tokens":{"default":0,"title":"Cache Read T'
    'okens","type":"integer"},"cache_write_tokens":{"default":0,"title":"Cache Write Tokens","type":"inte'
    'ger"},"cost":{"anyOf":[{"pattern":"^(?!^[-+.]*$)[+-]?0*\\\\d*\\\\.?\\\\d*$","type":"string"},{"type":"null'
    '"}],"default":null,"title":"Cost"},"details":{"additionalProperties":{"type":"integer"},"title":"Det'
    'ails","type":"object"},"input_audio_tokens":{"default":0,"title":"Input Audio Tokens","type":"intege'
    'r"},"input_tokens":{"default":0,"title":"Input Tokens","type":"integer"},"output_audio_tokens":{"def'
    'ault":0,"title":"Output Audio Tokens","type":"integer"},"output_tokens":{"default":0,"title":"Output'
    ' Tokens","type":"integer"}},"title":"RequestUsage","type":"object"},"RetryPromptPart":{"additionalPr'
    'operties":false,"properties":{"content":{"anyOf":[{"items":{"$ref":"#/$defs/ErrorDetails"},"type":"a'
    'rray"},{"type":"string"}],"title":"Content"},"part_kind":{"const":"retry-prompt","default":"retry-pr'
    'ompt","title":"Part Kind","type":"string"},"timestamp":{"format":"date-time","title":"Timestamp","ty'
    'pe":"string"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"tool_name":{"anyOf":[{"type":'
    '"string"},{"type":"null"}],"default":null,"title":"Tool Name"}},"required":["content"],"title":"Retr'
    'yPromptPart","type":"object"},"SystemPromptPart":{"additionalProperties":false,"properties":{"conten'
    't":{"title":"Content","type":"string"},"dynamic_ref":{"anyOf":[{"type":"string"},{"type":"null"}],"d'
    'efault":null,"title":"Dynamic Ref"},"part_kind":{"const":"system-prompt","default":"system-prompt","'
    'title":"Part Kind","type":"string"},"timestamp":{"format":"date-time","title":"Timestamp","type":"st'
    'ring"}},"required":["content"],"title":"SystemPromptPart","type":"object"},"TextContent":{"additiona'
    'lProperties":false,"properties":{"content":{"title":"Content","type":"string"},"kind":{"const":"text'
    '-content","default":"text-content","title":"Kind","type":"string"},"metadata":{"default":null,"title'
    '":"Metadata"}},"required":["content"],"title":"TextContent","type":"object"},"TextPart":{"additional'
    'Properties":false,"properties":{"content":{"title":"Content","type":"string"},"id":{"anyOf":[{"type"'
    ':"string"},{"type":"null"}],"default":null,"title":"Id"},"part_kind":{"const":"text","default":"text'
    '","title":"Part Kind","type":"string"},"provider_details":{"anyOf":[{"additionalProperties":true,"ty'
    'pe":"object"},{"type":"null"}],"default":null,"title":"Provider Details"},"provider_name":{"anyOf":['
    '{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Name"}},"required":["content"],"'
    'title":"TextPart","type":"object"},"ThinkingPart":{"additionalProperties":false,"properties":{"conte'
    'nt":{"title":"Content","type":"string"},"id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":'
    'null,"title":"Id"},"part_kind":{"const":"thinking","default":"thinking","title":"Part Kind","type":"'
    'string"},"provider_details":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}]'
    ',"default":null,"title":"Provider Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"nul'
    'l"}],"default":null,"title":"Provider Name"},"signature":{"anyOf":[{"type":"string"},{"type":"null"}'
    '],"default":null,"title":"Signature"}},"required":["content"],"title":"ThinkingPart","type":"object"'
    '},"ToolAvailabilityDeltaPart":{"additionalProperties":false,"properties":{"part_kind":{"const":"tool'
    '-availability-delta","default":"tool-availability-delta","title":"Part Kind","type":"string"},"tool_'
    'call_id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Tool Call Id"},"tools_'
    'added":{"items":{"type":"string"},"title":"Tools Added","type":"array"}},"title":"ToolAvailabilityDe'
    'ltaPart","type":"object"},"ToolCallPart":{"additionalProperties":false,"properties":{"args":{"anyOf"'
    ':[{"type":"string"},{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"t'
    'itle":"Args"},"id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Id"},"part_k'
    'ind":{"const":"tool-call","default":"tool-call","title":"Part Kind","type":"string"},"provider_detai'
    'ls":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":'
    '"Provider Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"tit'
    'le":"Provider Name"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"anyOf":[{'
    '"enum":["tool-search","capability-load"],"type":"string"},{"type":"null"}],"default":null,"title":"T'
    'ool Kind"},"tool_name":{"title":"Tool Name","type":"string"}},"required":["tool_name"],"title":"Tool'
    'CallPart","type":"object"},"ToolReturnContent":{"oneOf":[{},{"additionalProperties":{"$ref":"#/$defs'
    '/ToolReturnContent"},"type":"object"},{"items":{"$ref":"#/$defs/ToolReturnContent"},"type":"array"}]'
    '},"ToolReturnPart":{"additionalProperties":false,"properties":{"content":{"$ref":"#/$defs/ToolReturn'
    'Content"},"metadata":{"default":null,"title":"Metadata"},"outcome":{"default":"success","enum":["suc'
    'cess","failed","denied","interrupted"],"title":"Outcome","type":"string"},"part_kind":{"const":"tool'
    '-return","default":"tool-return","title":"Part Kind","type":"string"},"timestamp":{"format":"date-ti'
    'me","title":"Timestamp","type":"string"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"to'
    'ol_kind":{"anyOf":[{"enum":["tool-search","capability-load"],"type":"string"},{"type":"null"}],"defa'
    'ult":null,"title":"Tool Kind"},"tool_name":{"title":"Tool Name","type":"string"}},"required":["tool_'
    'name","content"],"title":"ToolReturnPart","type":"object"},"ToolSearchArgs":{"additionalProperties":'
    'false,"description":"Typed arguments for a tool-search call.\\n\\nCarried on\\n[`NativeToolSearchCallPa'
    "rt.args`][pydantic_ai.messages.NativeToolSearchCallPart.args]\\n(native server-side path) and\\n[`Tool"
    "SearchCallPart.args`][pydantic_ai.messages.ToolSearchCallPart.args]\\n(local-fallback path) as the ca"
    "nonical cross-provider shape. Each adapter\\nnormalizes its provider's wire format into this shape on"
    ' parse, and rebuilds the\\nwire format from this shape on emit.","properties":{"queries":{"items":{"t'
    'ype":"string"},"title":"Queries","type":"array"}},"required":["queries"],"title":"ToolSearchArgs","t'
    'ype":"object"},"ToolSearchCallPart":{"additionalProperties":false,"properties":{"args":{"anyOf":[{"t'
    'ype":"string"},{"$ref":"#/$defs/ToolSearchArgs"},{"type":"null"}],"default":null,"title":"Args"},"id'
    '":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Id"},"part_kind":{"const":"to'
    'ol-call","default":"tool-call","title":"Part Kind","type":"string"},"provider_details":{"anyOf":[{"a'
    'dditionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Provider Details'
    '"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Nam'
    'e"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"const":"tool-search","defa'
    'ult":"tool-search","title":"Tool Kind","type":"string"},"tool_name":{"const":"search_tools","default'
    '":"search_tools","title":"Tool Name","type":"string"}},"title":"ToolSearchCallPart","type":"object"}'
    ',"ToolSearchMatch":{"additionalProperties":false,"description":"A single match in a tool-search resu'
    'lt.","properties":{"name":{"title":"Name","type":"string"}},"required":["name"],"title":"ToolSearchM'
    'atch","type":"object"},"ToolSearchReturnContent":{"additionalProperties":false,"description":"Typed '
    "return value of the framework-managed tool-search builtin.\\n\\nCarried on\\n[`NativeToolSearchReturnPa"
    "rt.content`][pydantic_ai.messages.NativeToolSearchReturnPart.content]\\n(native server-side path) and"
    "\\n[`ToolSearchReturnPart.content`][pydantic_ai.messages.ToolSearchReturnPart.content]\\n(local-fallba"
    'ck path) as the canonical cross-provider shape.","properties":{"discovered_tools":{"items":{"$ref":"'
    '#/$defs/ToolSearchMatch"},"title":"Discovered Tools","type":"array"},"message":{"title":"Message","t'
    'ype":"string"}},"required":["discovered_tools"],"title":"ToolSearchReturnContent","type":"object"},"'
    'ToolSearchReturnPart":{"additionalProperties":false,"properties":{"content":{"$ref":"#/$defs/ToolSea'
    'rchReturnContent"},"metadata":{"default":null,"title":"Metadata"},"outcome":{"default":"success","en'
    'um":["success","failed","denied","interrupted"],"title":"Outcome","type":"string"},"part_kind":{"con'
    'st":"tool-return","default":"tool-return","title":"Part Kind","type":"string"},"timestamp":{"format"'
    ':"date-time","title":"Timestamp","type":"string"},"tool_call_id":{"title":"Tool Call Id","type":"str'
    'ing"},"tool_kind":{"const":"tool-search","default":"tool-search","title":"Tool Kind","type":"string"'
    '},"tool_name":{"const":"search_tools","default":"search_tools","title":"Tool Name","type":"string"}}'
    ',"required":["content"],"title":"ToolSearchReturnPart","type":"object"},"UploadedFile":{"additionalP'
    'roperties":false,"description":"A reference to a file uploaded to a provider\'s file storage by ID.\\n'
    "\\nThis allows referencing files that have been uploaded via provider-specific file APIs\\nrather than"
    " providing the file content directly.\\n\\nSupported by:\\n\\n- [`AnthropicModel`][pydantic_ai.models.an"
    "thropic.AnthropicModel]\\n- [`OpenAIChatModel`][pydantic_ai.models.openai.OpenAIChatModel]\\n- [`OpenA"
    "IResponsesModel`][pydantic_ai.models.openai.OpenAIResponsesModel]\\n- [`BedrockConverseModel`][pydant"
    "ic_ai.models.bedrock.BedrockConverseModel]\\n- [`GoogleModel`][pydantic_ai.models.google.GoogleModel]"
    " (Gemini API: [Files API](https://ai.google.dev/gemini-api/docs/files) URIs, Google Cloud: GCS `gs:/"
    '/` URIs)\\n- [`XaiModel`][pydantic_ai.models.xai.XaiModel]","properties":{"file_id":{"title":"File Id'
    '","type":"string"},"identifier":{"description":"The identifier of the file, such as a unique ID.\\n\\n'
    "This identifier can be provided to the model in a message to allow it to refer to this file in a too"
    "l call argument,\\nand the tool can look up the file in question by iterating over the message histor"
    "y and finding the matching `UploadedFile`.\\n\\nThis identifier is only automatically passed to the mo"
    "del when the `UploadedFile` is returned by a tool.\\nIf you're passing the `UploadedFile` as a user m"
    "essage, it's up to you to include a separate text part with the identifier,\\ne.g. \\\"This is file <id"
    'entifier>:\\" preceding the `UploadedFile`.","readOnly":true,"title":"Identifier","type":"string"},"k'
    'ind":{"const":"uploaded-file","default":"uploaded-file","title":"Kind","type":"string"},"media_type"'
    ':{"description":"Return the media type of the file, inferred from `file_id` if not explicitly provid'
    "ed.\\n\\nNote: Inference relies on the file extension in `file_id`.\\nFor opaque file IDs (e.g., `'file"
    "-abc123'`), the media type will default to `'application/octet-stream'`.\\nInference relies on Python"
    "'s `mimetypes` module, whose results may vary across platforms.\\n\\nRequired by some providers (e.g.,"
    ' Bedrock) for certain file types.","readOnly":true,"title":"Media Type","type":"string"},"provider_n'
    'ame":{"enum":["anthropic","openai","google","google-cloud","google-gla","google-vertex","bedrock","x'
    'ai"],"title":"Provider Name","type":"string"},"vendor_metadata":{"anyOf":[{"additionalProperties":tr'
    'ue,"type":"object"},{"type":"null"}],"default":null,"title":"Vendor Metadata"}},"required":["file_id'
    '","provider_name","media_type","identifier"],"title":"UploadedFile","type":"object"},"UserPromptPart'
    '":{"additionalProperties":false,"properties":{"content":{"anyOf":[{"type":"string"},{"items":{"anyOf'
    '":[{"type":"string"},{"$ref":"#/$defs/TextContent"},{"discriminator":{"mapping":{"audio-url":"#/$def'
    's/AudioUrl","binary":"#/$defs/BinaryContent","document-url":"#/$defs/DocumentUrl","image-url":"#/$de'
    'fs/ImageUrl","uploaded-file":"#/$defs/UploadedFile","video-url":"#/$defs/VideoUrl"},"propertyName":"'
    'kind"},"oneOf":[{"$ref":"#/$defs/ImageUrl"},{"$ref":"#/$defs/AudioUrl"},{"$ref":"#/$defs/DocumentUrl'
    '"},{"$ref":"#/$defs/VideoUrl"},{"$ref":"#/$defs/BinaryContent"},{"$ref":"#/$defs/UploadedFile"}]},{"'
    '$ref":"#/$defs/CachePoint"}]},"type":"array"}],"title":"Content"},"part_kind":{"const":"user-prompt"'
    ',"default":"user-prompt","title":"Part Kind","type":"string"},"timestamp":{"format":"date-time","tit'
    'le":"Timestamp","type":"string"}},"required":["content"],"title":"UserPromptPart","type":"object"},"'
    'VideoUrl":{"additionalProperties":false,"description":"A URL to a video.","properties":{"force_downl'
    'oad":{"anyOf":[{"type":"boolean"},{"const":"allow-local","type":"string"}],"default":false,"title":"'
    'Force Download"},"identifier":{"description":"The identifier of the file, such as a unique ID.\\n\\nTh'
    "is identifier can be provided to the model in a message to allow it to refer to this file in a tool "
    "call argument,\\nand the tool can look up the file in question by iterating over the message history "
    "and finding the matching `FileUrl`.\\n\\nThis identifier is only automatically passed to the model whe"
    "n the `FileUrl` is returned by a tool.\\nIf you're passing the `FileUrl` as a user message, it's up t"
    'o you to include a separate text part with the identifier,\\ne.g. \\"This is file <identifier>:\\" prec'
    "eding the `FileUrl`.\\n\\nIt's also included in inline-text delimiters for providers that require inli"
    'ning text documents, so the model can\\ndistinguish multiple files.","readOnly":true,"title":"Identif'
    'ier","type":"string"},"kind":{"const":"video-url","default":"video-url","title":"Kind","type":"strin'
    'g"},"media_type":{"description":"Return the media type of the file, based on the URL or the provided'
    ' `media_type`.","readOnly":true,"title":"Media Type","type":"string"},"url":{"title":"Url","type":"s'
    'tring"},"vendor_metadata":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"'
    'default":null,"title":"Vendor Metadata"}},"required":["url","media_type","identifier"],"title":"Vide'
    'oUrl","type":"object"}},"items":{"discriminator":{"mapping":{"request":"#/$defs/ModelRequest","respo'
    'nse":"#/$defs/ModelResponse"},"propertyName":"kind"},"oneOf":[{"$ref":"#/$defs/ModelRequest"},{"$ref'
    '":"#/$defs/ModelResponse"}]},"type":"array"}'
)
V1_SERIALIZATION_SCHEMA_SHA256 = (
    "eee52e24877dd706e1b69de1a6f1de7cb82187b305e89927b4f6c28cba59ca87"
)

V1_VALIDATION_SCHEMA_JSON: str = (
    '{"$defs":{"AudioUrl":{"additionalProperties":false,"description":"A URL to an audio file.","properti'
    'es":{"force_download":{"anyOf":[{"type":"boolean"},{"const":"allow-local","type":"string"}],"default'
    '":false,"title":"Force Download"},"identifier":{"anyOf":[{"type":"string"},{"type":"null"}],"default'
    '":null,"title":"Identifier"},"kind":{"const":"audio-url","default":"audio-url","title":"Kind","type"'
    ':"string"},"media_type":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Media T'
    'ype"},"url":{"title":"Url","type":"string"},"vendor_metadata":{"anyOf":[{"additionalProperties":true'
    ',"type":"object"},{"type":"null"}],"default":null,"title":"Vendor Metadata"}},"required":["url"],"ti'
    'tle":"AudioUrl","type":"object"},"BinaryContent":{"additionalProperties":false,"description":"Binary'
    ' content, e.g. an audio or image file.","properties":{"data":{"format":"base64url","title":"Data","t'
    'ype":"string"},"identifier":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Ide'
    'ntifier"},"kind":{"const":"binary","default":"binary","title":"Kind","type":"string"},"media_type":{'
    '"anyOf":[{"enum":["audio/wav","audio/mpeg","audio/ogg","audio/flac","audio/aiff","audio/aac"],"type"'
    ':"string"},{"enum":["image/jpeg","image/png","image/gif","image/webp"],"type":"string"},{"enum":["ap'
    'plication/pdf","text/plain","text/csv","application/vnd.openxmlformats-officedocument.wordprocessing'
    'ml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/html","text/m'
    'arkdown","application/msword","application/vnd.ms-excel"],"type":"string"},{"type":"string"}],"title'
    '":"Media Type"},"vendor_metadata":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"n'
    'ull"}],"default":null,"title":"Vendor Metadata"}},"required":["data","media_type"],"title":"BinaryCo'
    'ntent","type":"object"},"CachePoint":{"additionalProperties":false,"properties":{"kind":{"const":"ca'
    'che-point","default":"cache-point","title":"Kind","type":"string"},"ttl":{"default":"5m","enum":["5m'
    '","1h"],"title":"Ttl","type":"string"}},"title":"CachePoint","type":"object"},"CompactionPart":{"add'
    'itionalProperties":false,"properties":{"content":{"anyOf":[{"type":"string"},{"type":"null"}],"defau'
    'lt":null,"title":"Content"},"id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title"'
    ':"Id"},"part_kind":{"const":"compaction","default":"compaction","title":"Part Kind","type":"string"}'
    ',"provider_details":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"defaul'
    't":null,"title":"Provider Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"de'
    'fault":null,"title":"Provider Name"}},"title":"CompactionPart","type":"object"},"DocumentUrl":{"addi'
    'tionalProperties":false,"description":"The URL of the document.","properties":{"force_download":{"an'
    'yOf":[{"type":"boolean"},{"const":"allow-local","type":"string"}],"default":false,"title":"Force Dow'
    'nload"},"identifier":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Identifier'
    '"},"kind":{"const":"document-url","default":"document-url","title":"Kind","type":"string"},"media_ty'
    'pe":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Media Type"},"url":{"title"'
    ':"Url","type":"string"},"vendor_metadata":{"anyOf":[{"additionalProperties":true,"type":"object"},{"'
    'type":"null"}],"default":null,"title":"Vendor Metadata"}},"required":["url"],"title":"DocumentUrl","'
    'type":"object"},"ErrorDetails":{"additionalProperties":false,"properties":{"ctx":{"additionalPropert'
    'ies":true,"title":"Ctx","type":"object"},"input":{"title":"Input"},"loc":{"items":{"anyOf":[{"type":'
    '"integer"},{"type":"string"}]},"title":"Loc","type":"array"},"msg":{"title":"Msg","type":"string"},"'
    'type":{"title":"Type","type":"string"},"url":{"title":"Url","type":"string"}},"required":["type","lo'
    'c","msg","input"],"title":"ErrorDetails","type":"object"},"FilePart":{"additionalProperties":false,"'
    'properties":{"content":{"$ref":"#/$defs/BinaryContent"},"id":{"anyOf":[{"type":"string"},{"type":"nu'
    'll"}],"default":null,"title":"Id"},"part_kind":{"const":"file","default":"file","title":"Part Kind",'
    '"type":"string"},"provider_details":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":'
    '"null"}],"default":null,"title":"Provider Details"},"provider_name":{"anyOf":[{"type":"string"},{"ty'
    'pe":"null"}],"default":null,"title":"Provider Name"}},"required":["content"],"title":"FilePart","typ'
    'e":"object"},"ImageUrl":{"additionalProperties":false,"description":"A URL to an image.","properties'
    '":{"force_download":{"anyOf":[{"type":"boolean"},{"const":"allow-local","type":"string"}],"default":'
    'false,"title":"Force Download"},"identifier":{"anyOf":[{"type":"string"},{"type":"null"}],"default":'
    'null,"title":"Identifier"},"kind":{"const":"image-url","default":"image-url","title":"Kind","type":"'
    'string"},"media_type":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Media Typ'
    'e"},"url":{"title":"Url","type":"string"},"vendor_metadata":{"anyOf":[{"additionalProperties":true,"'
    'type":"object"},{"type":"null"}],"default":null,"title":"Vendor Metadata"}},"required":["url"],"titl'
    'e":"ImageUrl","type":"object"},"LoadCapabilityArgs":{"additionalProperties":false,"description":"Typ'
    'ed arguments for a `load_capability` tool call.","properties":{"id":{"description":"The id of the ca'
    'pability to load.","title":"Id","type":"string"}},"required":["id"],"title":"LoadCapabilityArgs","ty'
    'pe":"object"},"LoadCapabilityCallPart":{"additionalProperties":false,"properties":{"args":{"anyOf":['
    '{"type":"string"},{"$ref":"#/$defs/LoadCapabilityArgs"},{"type":"null"}],"default":null,"title":"Arg'
    's"},"id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Id"},"part_kind":{"con'
    'st":"tool-call","default":"tool-call","title":"Part Kind","type":"string"},"provider_details":{"anyO'
    'f":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Provider '
    'Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provi'
    'der Name"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"const":"capability-'
    'load","default":"capability-load","title":"Tool Kind","type":"string"},"tool_name":{"const":"load_ca'
    'pability","default":"load_capability","title":"Tool Name","type":"string"}},"title":"LoadCapabilityC'
    'allPart","type":"object"},"LoadCapabilityReturn":{"additionalProperties":false,"description":"Typed '
    'return value for the `load_capability` tool.","properties":{"instructions":{"title":"Instructions","'
    'type":"string"}},"title":"LoadCapabilityReturn","type":"object"},"LoadCapabilityReturnPart":{"additi'
    'onalProperties":false,"properties":{"content":{"$ref":"#/$defs/LoadCapabilityReturn"},"metadata":{"d'
    'efault":null,"title":"Metadata"},"outcome":{"default":"success","enum":["success","failed","denied",'
    '"interrupted"],"title":"Outcome","type":"string"},"part_kind":{"const":"tool-return","default":"tool'
    '-return","title":"Part Kind","type":"string"},"timestamp":{"format":"date-time","title":"Timestamp",'
    '"type":"string"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"const":"capab'
    'ility-load","default":"capability-load","title":"Tool Kind","type":"string"},"tool_name":{"const":"l'
    'oad_capability","default":"load_capability","title":"Tool Name","type":"string"}},"required":["conte'
    'nt"],"title":"LoadCapabilityReturnPart","type":"object"},"ModelRequest":{"additionalProperties":fals'
    'e,"properties":{"conversation_id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title'
    '":"Conversation Id"},"instructions":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"tit'
    'le":"Instructions"},"kind":{"const":"request","default":"request","title":"Kind","type":"string"},"m'
    'etadata":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"ti'
    'tle":"Metadata"},"parts":{"items":{"oneOf":[{"$ref":"#/$defs/SystemPromptPart"},{"$ref":"#/$defs/Use'
    'rPromptPart"},{"$ref":"#/$defs/ToolSearchReturnPart"},{"$ref":"#/$defs/LoadCapabilityReturnPart"},{"'
    '$ref":"#/$defs/ToolReturnPart"},{"$ref":"#/$defs/RetryPromptPart"},{"$ref":"#/$defs/ToolAvailability'
    'DeltaPart"}]},"title":"Parts","type":"array"},"run_id":{"anyOf":[{"type":"string"},{"type":"null"}],'
    '"default":null,"title":"Run Id"},"state":{"default":"complete","enum":["complete","interrupted"],"ti'
    'tle":"State","type":"string"},"timestamp":{"anyOf":[{"format":"date-time","type":"string"},{"type":"'
    'null"}],"default":null,"title":"Timestamp"}},"required":["parts"],"title":"ModelRequest","type":"obj'
    'ect"},"ModelResponse":{"additionalProperties":false,"properties":{"conversation_id":{"anyOf":[{"type'
    '":"string"},{"type":"null"}],"default":null,"title":"Conversation Id"},"finish_reason":{"anyOf":[{"e'
    'num":["stop","length","content_filter","tool_call","error"],"type":"string"},{"type":"null"}],"defau'
    'lt":null,"title":"Finish Reason"},"kind":{"const":"response","default":"response","title":"Kind","ty'
    'pe":"string"},"metadata":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"d'
    'efault":null,"title":"Metadata"},"model_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default"'
    ':null,"title":"Model Name"},"parts":{"items":{"oneOf":[{"$ref":"#/$defs/TextPart"},{"$ref":"#/$defs/'
    'ToolSearchCallPart"},{"$ref":"#/$defs/LoadCapabilityCallPart"},{"$ref":"#/$defs/ToolCallPart"},{"$re'
    'f":"#/$defs/NativeToolSearchCallPart"},{"$ref":"#/$defs/NativeToolCallPart"},{"$ref":"#/$defs/Native'
    'ToolSearchReturnPart"},{"$ref":"#/$defs/NativeToolReturnPart"},{"$ref":"#/$defs/ThinkingPart"},{"$re'
    'f":"#/$defs/CompactionPart"},{"$ref":"#/$defs/FilePart"}]},"title":"Parts","type":"array"},"provider'
    '_details":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"t'
    'itle":"Provider Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":nul'
    'l,"title":"Provider Name"},"provider_response_id":{"anyOf":[{"type":"string"},{"type":"null"}],"defa'
    'ult":null,"title":"Provider Response Id"},"provider_url":{"anyOf":[{"type":"string"},{"type":"null"}'
    '],"default":null,"title":"Provider Url"},"run_id":{"anyOf":[{"type":"string"},{"type":"null"}],"defa'
    'ult":null,"title":"Run Id"},"state":{"default":"complete","enum":["complete","incomplete","suspended'
    '","interrupted"],"title":"State","type":"string"},"timestamp":{"format":"date-time","title":"Timesta'
    'mp","type":"string"},"usage":{"$ref":"#/$defs/RequestUsage"}},"required":["parts"],"title":"ModelRes'
    'ponse","type":"object"},"NativeToolCallPart":{"additionalProperties":false,"properties":{"args":{"an'
    'yOf":[{"type":"string"},{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":nul'
    'l,"title":"Args"},"id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Id"},"pa'
    'rt_kind":{"const":"builtin-tool-call","default":"builtin-tool-call","title":"Part Kind","type":"stri'
    'ng"},"provider_details":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"de'
    'fault":null,"title":"Provider Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}]'
    ',"default":null,"title":"Provider Name"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"to'
    'ol_kind":{"anyOf":[{"enum":["tool-search","capability-load"],"type":"string"},{"type":"null"}],"defa'
    'ult":null,"title":"Tool Kind"},"tool_name":{"title":"Tool Name","type":"string"}},"required":["tool_'
    'name"],"title":"NativeToolCallPart","type":"object"},"NativeToolReturnPart":{"additionalProperties":'
    'false,"properties":{"content":{"$ref":"#/$defs/ToolReturnContent"},"metadata":{"default":null,"title'
    '":"Metadata"},"outcome":{"default":"success","enum":["success","failed","denied","interrupted"],"tit'
    'le":"Outcome","type":"string"},"part_kind":{"const":"builtin-tool-return","default":"builtin-tool-re'
    'turn","title":"Part Kind","type":"string"},"provider_details":{"anyOf":[{"additionalProperties":true'
    ',"type":"object"},{"type":"null"}],"default":null,"title":"Provider Details"},"provider_name":{"anyO'
    'f":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Name"},"timestamp":{"format"'
    ':"date-time","title":"Timestamp","type":"string"},"tool_call_id":{"title":"Tool Call Id","type":"str'
    'ing"},"tool_kind":{"anyOf":[{"enum":["tool-search","capability-load"],"type":"string"},{"type":"null'
    '"}],"default":null,"title":"Tool Kind"},"tool_name":{"title":"Tool Name","type":"string"}},"required'
    '":["tool_name","content"],"title":"NativeToolReturnPart","type":"object"},"NativeToolSearchCallPart"'
    ':{"additionalProperties":false,"properties":{"args":{"anyOf":[{"type":"string"},{"$ref":"#/$defs/Too'
    'lSearchArgs"},{"type":"null"}],"default":null,"title":"Args"},"id":{"anyOf":[{"type":"string"},{"typ'
    'e":"null"}],"default":null,"title":"Id"},"part_kind":{"const":"builtin-tool-call","default":"builtin'
    '-tool-call","title":"Part Kind","type":"string"},"provider_details":{"anyOf":[{"additionalProperties'
    '":true,"type":"object"},{"type":"null"}],"default":null,"title":"Provider Details"},"provider_name":'
    '{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Name"},"tool_call_id":'
    '{"title":"Tool Call Id","type":"string"},"tool_kind":{"const":"tool-search","default":"tool-search",'
    '"title":"Tool Kind","type":"string"},"tool_name":{"const":"tool_search","default":"tool_search","tit'
    'le":"Tool Name","type":"string"}},"title":"NativeToolSearchCallPart","type":"object"},"NativeToolSea'
    'rchReturnPart":{"additionalProperties":false,"properties":{"content":{"$ref":"#/$defs/ToolSearchRetu'
    'rnContent"},"metadata":{"default":null,"title":"Metadata"},"outcome":{"default":"success","enum":["s'
    'uccess","failed","denied","interrupted"],"title":"Outcome","type":"string"},"part_kind":{"const":"bu'
    'iltin-tool-return","default":"builtin-tool-return","title":"Part Kind","type":"string"},"provider_de'
    'tails":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"titl'
    'e":"Provider Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"'
    'title":"Provider Name"},"timestamp":{"format":"date-time","title":"Timestamp","type":"string"},"tool'
    '_call_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"const":"tool-search","default":"too'
    'l-search","title":"Tool Kind","type":"string"},"tool_name":{"const":"tool_search","default":"tool_se'
    'arch","title":"Tool Name","type":"string"}},"required":["content"],"title":"NativeToolSearchReturnPa'
    'rt","type":"object"},"RequestUsage":{"additionalProperties":false,"properties":{"cache_audio_read_to'
    'kens":{"default":0,"title":"Cache Audio Read Tokens","type":"integer"},"cache_read_tokens":{"default'
    '":0,"title":"Cache Read Tokens","type":"integer"},"cache_write_tokens":{"default":0,"title":"Cache W'
    'rite Tokens","type":"integer"},"cost":{"anyOf":[{"type":"number"},{"pattern":"^(?!^[-+.]*$)[+-]?0*\\\\'
    'd*\\\\.?\\\\d*$","type":"string"},{"type":"null"}],"default":null,"title":"Cost"},"details":{"additional'
    'Properties":{"type":"integer"},"title":"Details","type":"object"},"input_audio_tokens":{"default":0,'
    '"title":"Input Audio Tokens","type":"integer"},"input_tokens":{"default":0,"title":"Input Tokens","t'
    'ype":"integer"},"output_audio_tokens":{"default":0,"title":"Output Audio Tokens","type":"integer"},"'
    'output_tokens":{"default":0,"title":"Output Tokens","type":"integer"}},"title":"RequestUsage","type"'
    ':"object"},"RetryPromptPart":{"additionalProperties":false,"properties":{"content":{"anyOf":[{"items'
    '":{"$ref":"#/$defs/ErrorDetails"},"type":"array"},{"type":"string"}],"title":"Content"},"part_kind":'
    '{"const":"retry-prompt","default":"retry-prompt","title":"Part Kind","type":"string"},"timestamp":{"'
    'format":"date-time","title":"Timestamp","type":"string"},"tool_call_id":{"title":"Tool Call Id","typ'
    'e":"string"},"tool_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Tool N'
    'ame"}},"required":["content"],"title":"RetryPromptPart","type":"object"},"SystemPromptPart":{"additi'
    'onalProperties":false,"properties":{"content":{"title":"Content","type":"string"},"dynamic_ref":{"an'
    'yOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Dynamic Ref"},"part_kind":{"const":'
    '"system-prompt","default":"system-prompt","title":"Part Kind","type":"string"},"timestamp":{"format"'
    ':"date-time","title":"Timestamp","type":"string"}},"required":["content"],"title":"SystemPromptPart"'
    ',"type":"object"},"TextContent":{"additionalProperties":false,"properties":{"content":{"title":"Cont'
    'ent","type":"string"},"kind":{"const":"text-content","default":"text-content","title":"Kind","type":'
    '"string"},"metadata":{"default":null,"title":"Metadata"}},"required":["content"],"title":"TextConten'
    't","type":"object"},"TextPart":{"additionalProperties":false,"properties":{"content":{"title":"Conte'
    'nt","type":"string"},"id":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Id"},'
    '"part_kind":{"const":"text","default":"text","title":"Part Kind","type":"string"},"provider_details"'
    ':{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Pr'
    'ovider Details"},"provider_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title"'
    ':"Provider Name"}},"required":["content"],"title":"TextPart","type":"object"},"ThinkingPart":{"addit'
    'ionalProperties":false,"properties":{"content":{"title":"Content","type":"string"},"id":{"anyOf":[{"'
    'type":"string"},{"type":"null"}],"default":null,"title":"Id"},"part_kind":{"const":"thinking","defau'
    'lt":"thinking","title":"Part Kind","type":"string"},"provider_details":{"anyOf":[{"additionalPropert'
    'ies":true,"type":"object"},{"type":"null"}],"default":null,"title":"Provider Details"},"provider_nam'
    'e":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Name"},"signature":'
    '{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Signature"}},"required":["conte'
    'nt"],"title":"ThinkingPart","type":"object"},"ToolAvailabilityDeltaPart":{"additionalProperties":fal'
    'se,"properties":{"part_kind":{"const":"tool-availability-delta","default":"tool-availability-delta",'
    '"title":"Part Kind","type":"string"},"tool_call_id":{"anyOf":[{"type":"string"},{"type":"null"}],"de'
    'fault":null,"title":"Tool Call Id"},"tools_added":{"items":{"type":"string"},"title":"Tools Added","'
    'type":"array"}},"title":"ToolAvailabilityDeltaPart","type":"object"},"ToolCallPart":{"additionalProp'
    'erties":false,"properties":{"args":{"anyOf":[{"type":"string"},{"additionalProperties":true,"type":"'
    'object"},{"type":"null"}],"default":null,"title":"Args"},"id":{"anyOf":[{"type":"string"},{"type":"n'
    'ull"}],"default":null,"title":"Id"},"part_kind":{"const":"tool-call","default":"tool-call","title":"'
    'Part Kind","type":"string"},"provider_details":{"anyOf":[{"additionalProperties":true,"type":"object'
    '"},{"type":"null"}],"default":null,"title":"Provider Details"},"provider_name":{"anyOf":[{"type":"st'
    'ring"},{"type":"null"}],"default":null,"title":"Provider Name"},"tool_call_id":{"title":"Tool Call I'
    'd","type":"string"},"tool_kind":{"anyOf":[{"enum":["tool-search","capability-load"],"type":"string"}'
    ',{"type":"null"}],"default":null,"title":"Tool Kind"},"tool_name":{"title":"Tool Name","type":"strin'
    'g"}},"required":["tool_name"],"title":"ToolCallPart","type":"object"},"ToolReturnContent":{"oneOf":['
    '{"discriminator":{"mapping":{"audio-url":"#/$defs/AudioUrl","binary":"#/$defs/BinaryContent","docume'
    'nt-url":"#/$defs/DocumentUrl","image-url":"#/$defs/ImageUrl","uploaded-file":"#/$defs/UploadedFile",'
    '"video-url":"#/$defs/VideoUrl"},"propertyName":"kind"},"oneOf":[{"$ref":"#/$defs/ImageUrl"},{"$ref":'
    '"#/$defs/AudioUrl"},{"$ref":"#/$defs/DocumentUrl"},{"$ref":"#/$defs/VideoUrl"},{"$ref":"#/$defs/Bina'
    'ryContent"},{"$ref":"#/$defs/UploadedFile"}]},{"additionalProperties":{"$ref":"#/$defs/ToolReturnCon'
    'tent"},"type":"object"},{"items":{"$ref":"#/$defs/ToolReturnContent"},"type":"array"},{}]},"ToolRetu'
    'rnPart":{"additionalProperties":false,"properties":{"content":{"$ref":"#/$defs/ToolReturnContent"},"'
    'metadata":{"default":null,"title":"Metadata"},"outcome":{"default":"success","enum":["success","fail'
    'ed","denied","interrupted"],"title":"Outcome","type":"string"},"part_kind":{"const":"tool-return","d'
    'efault":"tool-return","title":"Part Kind","type":"string"},"timestamp":{"format":"date-time","title"'
    ':"Timestamp","type":"string"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"'
    'anyOf":[{"enum":["tool-search","capability-load"],"type":"string"},{"type":"null"}],"default":null,"'
    'title":"Tool Kind"},"tool_name":{"title":"Tool Name","type":"string"}},"required":["tool_name","cont'
    'ent"],"title":"ToolReturnPart","type":"object"},"ToolSearchArgs":{"additionalProperties":false,"desc'
    'ription":"Typed arguments for a tool-search call.\\n\\nCarried on\\n[`NativeToolSearchCallPart.args`][p'
    "ydantic_ai.messages.NativeToolSearchCallPart.args]\\n(native server-side path) and\\n[`ToolSearchCallP"
    "art.args`][pydantic_ai.messages.ToolSearchCallPart.args]\\n(local-fallback path) as the canonical cro"
    "ss-provider shape. Each adapter\\nnormalizes its provider's wire format into this shape on parse, and"
    ' rebuilds the\\nwire format from this shape on emit.","properties":{"queries":{"items":{"type":"strin'
    'g"},"title":"Queries","type":"array"}},"required":["queries"],"title":"ToolSearchArgs","type":"objec'
    't"},"ToolSearchCallPart":{"additionalProperties":false,"properties":{"args":{"anyOf":[{"type":"strin'
    'g"},{"$ref":"#/$defs/ToolSearchArgs"},{"type":"null"}],"default":null,"title":"Args"},"id":{"anyOf":'
    '[{"type":"string"},{"type":"null"}],"default":null,"title":"Id"},"part_kind":{"const":"tool-call","d'
    'efault":"tool-call","title":"Part Kind","type":"string"},"provider_details":{"anyOf":[{"additionalPr'
    'operties":true,"type":"object"},{"type":"null"}],"default":null,"title":"Provider Details"},"provide'
    'r_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Provider Name"},"tool_c'
    'all_id":{"title":"Tool Call Id","type":"string"},"tool_kind":{"const":"tool-search","default":"tool-'
    'search","title":"Tool Kind","type":"string"},"tool_name":{"const":"search_tools","default":"search_t'
    'ools","title":"Tool Name","type":"string"}},"title":"ToolSearchCallPart","type":"object"},"ToolSearc'
    'hMatch":{"additionalProperties":false,"description":"A single match in a tool-search result.","prope'
    'rties":{"name":{"title":"Name","type":"string"}},"required":["name"],"title":"ToolSearchMatch","type'
    '":"object"},"ToolSearchReturnContent":{"additionalProperties":false,"description":"Typed return valu'
    "e of the framework-managed tool-search builtin.\\n\\nCarried on\\n[`NativeToolSearchReturnPart.content`"
    "][pydantic_ai.messages.NativeToolSearchReturnPart.content]\\n(native server-side path) and\\n[`ToolSea"
    "rchReturnPart.content`][pydantic_ai.messages.ToolSearchReturnPart.content]\\n(local-fallback path) as"
    ' the canonical cross-provider shape.","properties":{"discovered_tools":{"items":{"$ref":"#/$defs/Too'
    'lSearchMatch"},"title":"Discovered Tools","type":"array"},"message":{"title":"Message","type":"strin'
    'g"}},"required":["discovered_tools"],"title":"ToolSearchReturnContent","type":"object"},"ToolSearchR'
    'eturnPart":{"additionalProperties":false,"properties":{"content":{"$ref":"#/$defs/ToolSearchReturnCo'
    'ntent"},"metadata":{"default":null,"title":"Metadata"},"outcome":{"default":"success","enum":["succe'
    'ss","failed","denied","interrupted"],"title":"Outcome","type":"string"},"part_kind":{"const":"tool-r'
    'eturn","default":"tool-return","title":"Part Kind","type":"string"},"timestamp":{"format":"date-time'
    '","title":"Timestamp","type":"string"},"tool_call_id":{"title":"Tool Call Id","type":"string"},"tool'
    '_kind":{"const":"tool-search","default":"tool-search","title":"Tool Kind","type":"string"},"tool_nam'
    'e":{"const":"search_tools","default":"search_tools","title":"Tool Name","type":"string"}},"required"'
    ':["content"],"title":"ToolSearchReturnPart","type":"object"},"UploadedFile":{"additionalProperties":'
    'false,"description":"A reference to a file uploaded to a provider\'s file storage by ID.\\n\\nThis allo'
    "ws referencing files that have been uploaded via provider-specific file APIs\\nrather than providing "
    "the file content directly.\\n\\nSupported by:\\n\\n- [`AnthropicModel`][pydantic_ai.models.anthropic.Ant"
    "hropicModel]\\n- [`OpenAIChatModel`][pydantic_ai.models.openai.OpenAIChatModel]\\n- [`OpenAIResponsesM"
    "odel`][pydantic_ai.models.openai.OpenAIResponsesModel]\\n- [`BedrockConverseModel`][pydantic_ai.model"
    "s.bedrock.BedrockConverseModel]\\n- [`GoogleModel`][pydantic_ai.models.google.GoogleModel] (Gemini AP"
    "I: [Files API](https://ai.google.dev/gemini-api/docs/files) URIs, Google Cloud: GCS `gs://` URIs)\\n-"
    ' [`XaiModel`][pydantic_ai.models.xai.XaiModel]","properties":{"file_id":{"title":"File Id","type":"s'
    'tring"},"identifier":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Identifier'
    '"},"kind":{"const":"uploaded-file","default":"uploaded-file","title":"Kind","type":"string"},"media_'
    'type":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Media Type"},"provider_na'
    'me":{"enum":["anthropic","openai","google","google-cloud","google-gla","google-vertex","bedrock","xa'
    'i"],"title":"Provider Name","type":"string"},"vendor_metadata":{"anyOf":[{"additionalProperties":tru'
    'e,"type":"object"},{"type":"null"}],"default":null,"title":"Vendor Metadata"}},"required":["file_id"'
    ',"provider_name"],"title":"UploadedFile","type":"object"},"UserPromptPart":{"additionalProperties":f'
    'alse,"properties":{"content":{"anyOf":[{"type":"string"},{"items":{"anyOf":[{"type":"string"},{"$ref'
    '":"#/$defs/TextContent"},{"discriminator":{"mapping":{"audio-url":"#/$defs/AudioUrl","binary":"#/$de'
    'fs/BinaryContent","document-url":"#/$defs/DocumentUrl","image-url":"#/$defs/ImageUrl","uploaded-file'
    '":"#/$defs/UploadedFile","video-url":"#/$defs/VideoUrl"},"propertyName":"kind"},"oneOf":[{"$ref":"#/'
    '$defs/ImageUrl"},{"$ref":"#/$defs/AudioUrl"},{"$ref":"#/$defs/DocumentUrl"},{"$ref":"#/$defs/VideoUr'
    'l"},{"$ref":"#/$defs/BinaryContent"},{"$ref":"#/$defs/UploadedFile"}]},{"$ref":"#/$defs/CachePoint"}'
    ']},"type":"array"}],"title":"Content"},"part_kind":{"const":"user-prompt","default":"user-prompt","t'
    'itle":"Part Kind","type":"string"},"timestamp":{"format":"date-time","title":"Timestamp","type":"str'
    'ing"}},"required":["content"],"title":"UserPromptPart","type":"object"},"VideoUrl":{"additionalPrope'
    'rties":false,"description":"A URL to a video.","properties":{"force_download":{"anyOf":[{"type":"boo'
    'lean"},{"const":"allow-local","type":"string"}],"default":false,"title":"Force Download"},"identifie'
    'r":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Identifier"},"kind":{"const"'
    ':"video-url","default":"video-url","title":"Kind","type":"string"},"media_type":{"anyOf":[{"type":"s'
    'tring"},{"type":"null"}],"default":null,"title":"Media Type"},"url":{"title":"Url","type":"string"},'
    '"vendor_metadata":{"anyOf":[{"additionalProperties":true,"type":"object"},{"type":"null"}],"default"'
    ':null,"title":"Vendor Metadata"}},"required":["url"],"title":"VideoUrl","type":"object"}},"items":{"'
    'discriminator":{"mapping":{"request":"#/$defs/ModelRequest","response":"#/$defs/ModelResponse"},"pro'
    'pertyName":"kind"},"oneOf":[{"$ref":"#/$defs/ModelRequest"},{"$ref":"#/$defs/ModelResponse"}]},"type'
    '":"array"}'
)
V1_VALIDATION_SCHEMA_SHA256 = (
    "9c13a89a0edcd9ead2e9b64f35413b035d06684a9f148f1589e96af7cefd7f97"
)
