#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
@author  : Hu Ji
@file    : meta.py
@time    : 2018/11/25
@site    :
@software: PyCharm

              ,----------------,              ,---------,
         ,-----------------------,          ,"        ,"|
       ,"                      ,"|        ,"        ,"  |
      +-----------------------+  |      ,"        ,"    |
      |  .-----------------.  |  |     +---------+      |
      |  |                 |  |  |     | -==----'|      |
      |  | $ sudo rm -rf / |  |  |     |         |      |
      |  |                 |  |  |/----|`---=    |      |
      |  |                 |  |  |   ,/|==== ooo |      ;
      |  |                 |  |  |  // |(((( [33]|    ,"
      |  `-----------------'  |," .;'| |((((     |  ,"
      +-----------------------+  ;;  | |         |,"
         /_)______________(_/  //'   | +---------+
    ___________________________/___  `,
   /  oooooooooooooooo  .o.  oooo /,   `,"-----------
  / ==ooooooooooooooo==.o.  ooo= //   ,``--{)B     ,"
 /_==__==========__==_ooo__ooo=_/'   /___________,"
"""

class __MissingType:
    __eq__ = lambda l, r: \
        l is r or type(l) is type(r)
    __repr__ = lambda _: "__missing__"
    __bool__ = lambda _: False


def __is_develop():
    import os
    path = os.path.join(os.path.dirname(__file__), "develop")
    return os.path.isdir(path)


__name__ = "linktools"
__version__ = "{{ version }}"
__release__ = {{ "True" if release else "False" }}
__develop__ = __is_develop()
__missing__ = __MissingType()
__ep_script__ = "linktools_scripts"
__ep_updater__ = "linktools_updater"
__description__ = f"""\
    ___       __   __              __
   / (_)___  / /__/ /_____  ____  / /____
  / / / __ \\/ //_/ __/ __ \\/ __ \\/ / ___/  linktools toolkit (v{{ version }})
 / / / / / / ,< / /_/ /_/ / /_/ / (__  )   by: Hu Ji <669898595@qq.com>
/_/_/_/ /_/_/|_|\\__/\\____/\\____/_/____/
"""

del __is_develop
del __MissingType
