#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Contract-owned normalization for the supported JSON Schema subset."""

import json
from collections.abc import Mapping, Sequence
from typing import cast

from jsonschema import Draft202012Validator
from jsonschema.exceptions import SchemaError
from pydantic import BaseModel
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaValue
from pydantic_core import core_schema

from ..core import JsonValue, canonical_json_bytes
from ..errors import AIError, ErrorCode

_SCHEMA_MAP_KEYWORDS = frozenset(
    {"properties", "patternProperties", "dependentSchemas"}
)
_SCHEMA_VALUE_KEYWORDS = frozenset(
    {
        "additionalItems",
        "additionalProperties",
        "contains",
        "contentSchema",
        "else",
        "if",
        "items",
        "not",
        "propertyNames",
        "then",
        "unevaluatedItems",
        "unevaluatedProperties",
    }
)
_SCHEMA_ARRAY_KEYWORDS = frozenset(
    {"allOf", "anyOf", "oneOf", "prefixItems"}
)
_LITERAL_JSON_KEYWORDS = frozenset(
    {"const", "default", "enum", "examples"}
)
_GENERATED_MODEL_TITLE_MARKER: dict[str, JsonValue] = {
    "__linktools_generated_model_title__": True,
}


class _GeneratedModelTitleSchemaGenerator(GenerateJsonSchema):
    def model_schema(
        self,
        schema: core_schema.ModelSchema,
    ) -> JsonSchemaValue:
        result = super().model_schema(schema)
        model = schema["cls"]
        if (
            isinstance(model, type)
            and issubclass(model, BaseModel)
            and _uses_default_model_title(model, result)
        ):
            result["title"] = _GENERATED_MODEL_TITLE_MARKER
        return result


def canonicalize_pydantic_model_schema(
    model: type[BaseModel],
) -> "dict[str, JsonValue]":
    """Canonicalize a Pydantic model schema without generated model titles."""
    if not isinstance(model, type) or not issubclass(model, BaseModel):
        raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
    try:
        generated = cast(
            "dict[str, object]",
            model.model_json_schema(
                schema_generator=_GeneratedModelTitleSchemaGenerator,
            ),
        )
        title_paths: set[tuple[str | int, ...]] = set()
        _replace_generated_title_markers(generated, (), title_paths)
        return canonicalize_json_schema(
            cast(Mapping[str, JsonValue], generated),
            generated_title_paths=frozenset(title_paths),
        )
    except AIError:
        raise
    except Exception as error:
        raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID) from error


def canonicalize_json_schema(
    schema: Mapping[str, JsonValue],
    *,
    generated_title_paths: frozenset[tuple[str | int, ...]] = frozenset(),
) -> "dict[str, JsonValue]":
    """Return the deterministic form of one supported JSON Schema.

    ``generated_title_paths`` contains paths in the input schema whose title
    was proven to be generated by the caller.  Titles are otherwise durable
    schema data and are preserved.
    """
    if not isinstance(schema, Mapping):
        raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
    try:
        copied = cast(
            "dict[str, JsonValue]",
            json.loads(
                canonical_json_bytes(cast(JsonValue, dict(schema))).decode("utf-8")
            ),
        )
        Draft202012Validator.check_schema(copied)
        reachable = _reachable_definitions(copied)
        result = _rewrite_schema(
            copied,
            reachable,
            generated_title_paths,
            (),
        )
        if reachable:
            definitions = copied.get("$defs")
            if not isinstance(definitions, Mapping):
                raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
            result["$defs"] = {
                f"d{index}": _rewrite_schema(
                    definitions[name],
                    reachable,
                    generated_title_paths,
                    ("$defs", name),
                )
                for index, name in enumerate(reachable)
            }
        else:
            result.pop("$defs", None)
        Draft202012Validator.check_schema(result)
        return cast("dict[str, JsonValue]", result)
    except AIError:
        raise
    except (TypeError, ValueError, SchemaError) as error:
        raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID) from error


def _uses_default_model_title(
    model: type[BaseModel],
    schema: Mapping[str, object],
) -> bool:
    config = model.model_config
    extra = config.get("json_schema_extra")
    if (
        config.get("title") is not None
        or config.get("model_title_generator") is not None
        or schema.get("title") != model.__name__
        or callable(extra)
        or isinstance(extra, Mapping)
        and "title" in extra
    ):
        return False
    hook = getattr(model, "__get_pydantic_json_schema__", None)
    base_hook = getattr(BaseModel, "__get_pydantic_json_schema__", None)
    return getattr(hook, "__func__", hook) is getattr(
        base_hook,
        "__func__",
        base_hook,
    )


def _replace_generated_title_markers(
    value: object,
    path: tuple[str | int, ...],
    paths: set[tuple[str | int, ...]],
) -> None:
    if isinstance(value, dict):
        if value.get("title") == _GENERATED_MODEL_TITLE_MARKER:
            paths.add((*path, "title"))
            value["title"] = ""
        for key, child in value.items():
            _replace_generated_title_markers(child, (*path, key), paths)
    elif isinstance(value, list):
        for index, child in enumerate(value):
            _replace_generated_title_markers(child, (*path, index), paths)


def _reachable_definitions(schema: Mapping[str, JsonValue]) -> tuple[str, ...]:
    definitions = schema.get("$defs")
    if definitions is not None and not isinstance(definitions, Mapping):
        raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
    refs: dict[str, list[str]] = {"": []}

    def collect(node: object, owner: str, path: tuple[str | int, ...]) -> None:
        if isinstance(node, Mapping):
            for key in sorted(node):
                child = node[key]
                if key == "$defs":
                    if owner:
                        raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
                    continue
                if key in _LITERAL_JSON_KEYWORDS or key == "dependentRequired":
                    continue
                if key in _SCHEMA_MAP_KEYWORDS:
                    if not isinstance(child, Mapping):
                        continue
                    for name in sorted(child):
                        collect(child[name], owner, (*path, key, name))
                    continue
                if key in _SCHEMA_ARRAY_KEYWORDS:
                    if not isinstance(child, list):
                        continue
                    for index, nested in enumerate(child):
                        collect(nested, owner, (*path, key, index))
                    continue
                if key in _SCHEMA_VALUE_KEYWORDS:
                    collect(child, owner, (*path, key))
                    continue
                if key in {"$dynamicRef", "$recursiveRef", "$recursiveAnchor"}:
                    raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
                if key == "$ref":
                    if not isinstance(child, str) or not child.startswith("#/$defs/"):
                        raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
                    refs.setdefault(owner, []).append(_decode_definition_pointer(child))
                    continue
        elif isinstance(node, list):
            for index, child in enumerate(node):
                collect(child, owner, (*path, index))

    collect(schema, "", ())
    if isinstance(definitions, Mapping):
        if any(not isinstance(name, str) for name in definitions):
            raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
        for name in sorted(definitions):
            refs.setdefault(name, [])
            collect(definitions[name], name, ("$defs", name))

    reachable: list[str] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(name: str) -> None:
        if name in visiting or name in visited:
            if name in visiting:
                raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
            return
        if not isinstance(definitions, Mapping) or name not in definitions:
            raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
        visiting.add(name)
        reachable.append(name)
        for child in refs.get(name, ()):
            visit(child)
        visiting.remove(name)
        visited.add(name)

    for name in refs[""]:
        visit(name)
    return tuple(reachable)


def _rewrite_schema(
    value: object,
    reachable: Sequence[str],
    generated_title_paths: frozenset[tuple[str | int, ...]],
    path: tuple[str | int, ...],
) -> object:
    if isinstance(value, Mapping):
        result: dict[str, object] = {}
        for key, child in value.items():
            if key == "$defs":
                continue
            if key == "title" and (
                path in generated_title_paths
                or (*path, "title") in generated_title_paths
            ):
                continue
            if key in _LITERAL_JSON_KEYWORDS:
                result[str(key)] = child
                continue
            if key == "$ref":
                if not isinstance(child, str):
                    raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
                target = _decode_definition_pointer(child)
                if target not in reachable:
                    raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
                child = f"#/$defs/d{reachable.index(target)}"
                result[str(key)] = child
                continue
            if key in _SCHEMA_MAP_KEYWORDS:
                if not isinstance(child, Mapping):
                    result[str(key)] = child
                    continue
                result[str(key)] = {
                    str(name): _rewrite_schema(
                        child[name],
                        reachable,
                        generated_title_paths,
                        (*path, key, str(name)),
                    )
                    for name in sorted(child, key=str)
                }
                continue
            if key in _SCHEMA_ARRAY_KEYWORDS:
                if not isinstance(child, list):
                    result[str(key)] = child
                    continue
                result[str(key)] = [
                    _rewrite_schema(
                        nested,
                        reachable,
                        generated_title_paths,
                        (*path, key, index),
                    )
                    for index, nested in enumerate(child)
                ]
                continue
            if key in _SCHEMA_VALUE_KEYWORDS:
                result[str(key)] = _rewrite_schema(
                    child,
                    reachable,
                    generated_title_paths,
                    (*path, key),
                )
                continue
            result[str(key)] = child
        for key in ("required", "type"):
            current = result.get(key)
            if isinstance(current, list):
                result[key] = sorted(set(current), key=str)
        dependent = result.get("dependentRequired")
        if isinstance(dependent, Mapping):
            result["dependentRequired"] = {
                str(name): sorted(set(items), key=str)
                if isinstance(items, list)
                else items
                for name, items in dependent.items()
            }
        return result
    if isinstance(value, list):
        return [
            _rewrite_schema(child, reachable, generated_title_paths, (*path, index))
            for index, child in enumerate(value)
        ]
    return value


def _decode_definition_pointer(value: str) -> str:
    key = value.removeprefix("#/$defs/")
    if not key:
        raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
    result: list[str] = []
    index = 0
    while index < len(key):
        character = key[index]
        if character != "~":
            result.append(character)
            index += 1
            continue
        if index + 1 >= len(key) or key[index + 1] not in "01":
            raise AIError(ErrorCode.OUTPUT_CONTRACT_INVALID)
        result.append("/" if key[index + 1] == "1" else "~")
        index += 2
    return "".join(result)


__all__ = ["canonicalize_json_schema", "canonicalize_pydantic_model_schema"]
