dependencies: []

dev-dependencies: []

release-dependencies:
  - linktools[cli]>=0.9.0

optional-dependencies:
  lief:
    # 为grep提供服务，可解析apk、elf等文件格式
    # (注意：macOS需要使用以下命令安装libmagic: brew install libmagic）
    # Provide services for grep, can parse apk, elf and other file formats
    # (Note: macOS needs to install libmagic using the following command: brew install libmagic)
    - lief>0.10.1
    - python-magic; platform_system=="Linux"
    - python-magic; platform_system=="Darwin"
    - python-magic-bin; platform_system=="Windows"
