access_control:
  default_policy: deny
  rules:
    {%- for domain, rule in container.acl_rules.items() %}
    - domain:
        - "{{ domain }}"
      {% if rule["Subject"] -%}
      subject:
        {% for subject in rule["Subject"] -%}
        - "{{ subject }}"
        {%- endfor %}
      {%- endif %}
      {% if rule["Policy"] -%}
      policy: '{{ rule["Policy"] }}'
      {%- else -%}
      policy: '{{ 'two_factor' if AUTHELIA_MIN_AUTH_LEVEL > 1 else 'one_factor' }}'
      {%- endif %}
    {%- endfor %}
    - domain:
        - "{{ NGINX_ROOT_DOMAIN }}"
        - "*.{{ NGINX_ROOT_DOMAIN }}"
      subject:
        - "group:admin"
        - "group:admins"
        - "group:super-admin"
      policy: '{{ 'two_factor' if AUTHELIA_MIN_AUTH_LEVEL > 1 else 'one_factor' }}'
