identity_providers:
  oidc:
    jwks:
#     {% raw %}
      - key: {{ secret "/secrets/identity_providers_oidc_jwks" | mindent 10 "|" | msquote }}
#     {% endraw %}
    clients:
#     {% for client in container.oidc_clients %}
      - client_id: '{{ client['ClientID'] }}'
        client_name: '{{ client['ClientName'] }}'
        client_secret: '{{ client['ClientSecret'] }}'
        public: false
        authorization_policy: '{{ 'two_factor' if AUTHELIA_MIN_AUTH_LEVEL > 1 else 'one_factor' }}'
        consent_mode: 'implicit'
        require_pkce: false
        pkce_challenge_method: ''
        redirect_uris:
#         {% for url in client['RedirectURLs'] %}
          - '{{ url }}'
#         {% endfor %}
        scopes:
#         {% for item in client['Scopes'].split() %}
          - '{{ item }}'
#         {% endfor %}
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
#       {% endfor %}
