location / {
    include /etc/nginx/conf.d/snippets/header.conf;
    set $target_url "http://authelia:9091";
    proxy_pass $target_url;
}

location /auth-admin {
    include /etc/nginx/conf.d/snippets/header.conf;
    include /etc/nginx/conf.d/snippets/auth.conf;
    set $target_url "http://authelia-admin:9093";
    proxy_pass $target_url;
}
