-- linktools-ai canonical MySQL schema reference.
--
-- This file is manually reviewed DBA input, not an application bootstrap.
-- Provisioning is performed only by the explicit migrate/provision API.
-- All physical tables use the ai_ prefix; there is no schema manifest table.
-- Every column is commented, digest columns are utf8mb4_bin CHAR(64),
-- tenant_id is VARCHAR(128), operational timestamps are adjacent,
-- composite unique/index keys contain at most three physical columns,
-- and this schema deliberately contains no foreign keys or FLOAT columns.

SET NAMES utf8mb4;

CREATE TABLE `ai_asset_changes` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_asset_changes.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_changes.namespace_digest',
  `asset_key_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_changes.asset_key_digest',
  `asset_kind` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_changes.asset_kind',
  `asset_id` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_changes.asset_id',
  `entry_revision` BIGINT NOT NULL COMMENT 'Column ai_asset_changes.entry_revision',
  `store_revision` BIGINT NOT NULL COMMENT 'Column ai_asset_changes.store_revision',
  `etag` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_changes.etag',
  `size` BIGINT NOT NULL COMMENT 'Column ai_asset_changes.size',
  `status` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_changes.status',
  `object_store_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_asset_changes.object_store_id',
  `object_key` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_asset_changes.object_key',
  `metadata` JSON NOT NULL COMMENT 'Column ai_asset_changes.metadata',
  `modified_at` DATETIME NOT NULL COMMENT 'Column ai_asset_changes.modified_at',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_asset_changes.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_asset_changes.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_asset_changes_revision` (`namespace_digest`, `asset_key_digest`, `entry_revision`),
  KEY `ix_ai_asset_changes_revision` (`namespace_digest`, `store_revision`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_asset_changes';

CREATE TABLE `ai_asset_entries` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_asset_entries.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_entries.namespace_digest',
  `asset_key_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_entries.asset_key_digest',
  `asset_kind` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_entries.asset_kind',
  `asset_id` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_entries.asset_id',
  `entry_revision` BIGINT NOT NULL COMMENT 'Column ai_asset_entries.entry_revision',
  `store_revision` BIGINT NOT NULL COMMENT 'Column ai_asset_entries.store_revision',
  `etag` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_entries.etag',
  `size` BIGINT NOT NULL COMMENT 'Column ai_asset_entries.size',
  `status` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_entries.status',
  `object_store_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_asset_entries.object_store_id',
  `object_key` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_asset_entries.object_key',
  `metadata` JSON NOT NULL COMMENT 'Column ai_asset_entries.metadata',
  `modified_at` DATETIME NOT NULL COMMENT 'Column ai_asset_entries.modified_at',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_asset_entries.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_asset_entries.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_asset_entries_identity` (`namespace_digest`, `asset_key_digest`),
  KEY `ix_ai_asset_entries_revision` (`namespace_digest`, `store_revision`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_asset_entries';

CREATE TABLE `ai_asset_heads` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_asset_heads.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_asset_heads.namespace_digest',
  `store_revision` BIGINT NOT NULL COMMENT 'Column ai_asset_heads.store_revision',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_asset_heads.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_asset_heads.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_asset_heads_namespace_digest` (`namespace_digest`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_asset_heads';

CREATE TABLE `ai_runtime_approvals` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_approvals.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_approvals.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_approvals.tenant_id',
  `approval_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_approvals.approval_id',
  `execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_approvals.execution_id',
  `operation_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_approvals.operation_id',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_approvals.status',
  `idempotency_key_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_approvals.idempotency_key_digest',
  `decision` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_approvals.decision',
  `decided_by` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_approvals.decided_by',
  `decision_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_approvals.decision_digest',
  `decided_at` DATETIME COMMENT 'Column ai_runtime_approvals.decided_at',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_approvals.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_approvals.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_approvals_namespace_digest_tenant_id_approval_id` (`namespace_digest`, `tenant_id`, `approval_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_approvals';

CREATE TABLE `ai_runtime_artifacts` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_artifacts.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_artifacts.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_artifacts.tenant_id',
  `artifact_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_artifacts.artifact_id',
  `execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_artifacts.execution_id',
  `producer` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_artifacts.producer',
  `media_type` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_artifacts.media_type',
  `object_store_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_artifacts.object_store_id',
  `object_key` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_artifacts.object_key',
  `object_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_artifacts.object_digest',
  `object_size` BIGINT NOT NULL COMMENT 'Column ai_runtime_artifacts.object_size',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_artifacts.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_artifacts.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_artifacts_namespace_digest_tenant_id_artifact_id` (`namespace_digest`, `tenant_id`, `artifact_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_artifacts';

CREATE TABLE `ai_runtime_evaluations` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_evaluations.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_evaluations.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_evaluations.tenant_id',
  `evaluation_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_evaluations.evaluation_id',
  `execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_evaluations.execution_id',
  `dataset_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_evaluations.dataset_id',
  `dataset_revision` BIGINT NOT NULL COMMENT 'Column ai_runtime_evaluations.dataset_revision',
  `evaluator_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_evaluations.evaluator_id',
  `evaluator_revision` BIGINT NOT NULL COMMENT 'Column ai_runtime_evaluations.evaluator_revision',
  `binding_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_evaluations.binding_digest',
  `output_schema_fingerprint` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_evaluations.output_schema_fingerprint',
  `artifact_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_evaluations.artifact_digest',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_evaluations.status',
  `revision` BIGINT NOT NULL COMMENT 'Column ai_runtime_evaluations.revision',
  `metrics` JSON NOT NULL COMMENT 'Column ai_runtime_evaluations.metrics',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_evaluations.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_evaluations.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_evaluations_namespace_digest_tenant_id_evaluation_id` (`namespace_digest`, `tenant_id`, `evaluation_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_evaluations';

CREATE TABLE `ai_runtime_events` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_events.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_events.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_events.tenant_id',
  `execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_events.execution_id',
  `sequence` BIGINT NOT NULL COMMENT 'Column ai_runtime_events.sequence',
  `identity_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_events.identity_digest',
  `event_type` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_events.event_type',
  `payload` JSON NOT NULL COMMENT 'Column ai_runtime_events.payload',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_events.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_events.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_events_namespace_digest_tenant_id_identity_digest` (`namespace_digest`, `tenant_id`, `identity_digest`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_events';

CREATE TABLE `ai_runtime_executions` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_executions.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_executions.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_executions.tenant_id',
  `execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_executions.execution_id',
  `session_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.session_id',
  `binding_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_executions.binding_digest',
  `parent_execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.parent_execution_id',
  `root_execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_executions.root_execution_id',
  `source_execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.source_execution_id',
  `base_execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.base_execution_id',
  `lineage_kind` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_executions.lineage_kind',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_executions.status',
  `revision` BIGINT NOT NULL COMMENT 'Column ai_runtime_executions.revision',
  `event_sequence` BIGINT NOT NULL COMMENT 'Column ai_runtime_executions.event_sequence',
  `agent_run_sequence` BIGINT NOT NULL COMMENT 'Column ai_runtime_executions.agent_run_sequence',
  `error_code` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.error_code',
  `safe_error_details` JSON NOT NULL COMMENT 'Column ai_runtime_executions.safe_error_details',
  `memory_scope` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.memory_scope',
  `conversation_step_run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.conversation_step_run_id',
  `output_schema_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.output_schema_id',
  `output_schema_revision` BIGINT COMMENT 'Column ai_runtime_executions.output_schema_revision',
  `output_schema_fingerprint` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.output_schema_fingerprint',
  `result_store_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.result_store_id',
  `result_object_key` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.result_object_key',
  `result_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_executions.result_digest',
  `result_size` BIGINT COMMENT 'Column ai_runtime_executions.result_size',
  `stop_reason` TEXT COMMENT 'Column ai_runtime_executions.stop_reason',
  `model_requests` BIGINT COMMENT 'Column ai_runtime_executions.model_requests',
  `tool_calls` BIGINT COMMENT 'Column ai_runtime_executions.tool_calls',
  `input_tokens` BIGINT COMMENT 'Column ai_runtime_executions.input_tokens',
  `output_tokens` BIGINT COMMENT 'Column ai_runtime_executions.output_tokens',
  `cache_read_tokens` BIGINT COMMENT 'Column ai_runtime_executions.cache_read_tokens',
  `cache_write_tokens` BIGINT COMMENT 'Column ai_runtime_executions.cache_write_tokens',
  `result_created_at` DATETIME COMMENT 'Column ai_runtime_executions.result_created_at',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_executions.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_executions.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_executions_namespace_digest_tenant_id_execution_id` (`namespace_digest`, `tenant_id`, `execution_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_executions';

CREATE TABLE `ai_runtime_external_calls` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_external_calls.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_external_calls.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_external_calls.tenant_id',
  `call_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_external_calls.call_id',
  `execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_external_calls.execution_id',
  `operation_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_external_calls.operation_id',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_external_calls.status',
  `idempotency_key_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_external_calls.idempotency_key_digest',
  `object_store_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_external_calls.object_store_id',
  `object_key` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_external_calls.object_key',
  `object_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_external_calls.object_digest',
  `object_size` BIGINT COMMENT 'Column ai_runtime_external_calls.object_size',
  `payload_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_external_calls.payload_digest',
  `supplied_at` DATETIME COMMENT 'Column ai_runtime_external_calls.supplied_at',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_external_calls.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_external_calls.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_external_calls_namespace_digest_tenant_id_call_id` (`namespace_digest`, `tenant_id`, `call_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_external_calls';

CREATE TABLE `ai_runtime_idempotency` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_idempotency.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_idempotency.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_idempotency.tenant_id',
  `runtime_domain` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_idempotency.runtime_domain',
  `scope` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_idempotency.scope',
  `key_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_idempotency.key_digest',
  `identity_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_idempotency.identity_digest',
  `request_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_idempotency.request_digest',
  `resource_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_idempotency.resource_id',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_idempotency.status',
  `result_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_idempotency.result_digest',
  `error_code` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_idempotency.error_code',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_idempotency.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_idempotency.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_idempotency_namespace_digest_tenant_id_identity_digest` (`namespace_digest`, `tenant_id`, `identity_digest`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_idempotency';

CREATE TABLE `ai_runtime_memories` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_memories.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_memories.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_memories.tenant_id',
  `memory_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_memories.memory_id',
  `memory_scope_key` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_memories.memory_scope_key',
  `object_store_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_memories.object_store_id',
  `object_key` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_memories.object_key',
  `object_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_memories.object_digest',
  `object_size` BIGINT NOT NULL COMMENT 'Column ai_runtime_memories.object_size',
  `metadata` JSON NOT NULL COMMENT 'Column ai_runtime_memories.metadata',
  `revision` BIGINT NOT NULL COMMENT 'Column ai_runtime_memories.revision',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_memories.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_memories.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_memories_namespace_digest_tenant_id_memory_id` (`namespace_digest`, `tenant_id`, `memory_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_memories';

CREATE TABLE `ai_runtime_operation_counters` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_operation_counters.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operation_counters.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operation_counters.tenant_id',
  `runtime_domain` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operation_counters.runtime_domain',
  `resource_kind` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operation_counters.resource_kind',
  `resource_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operation_counters.resource_id',
  `stream_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operation_counters.stream_digest',
  `last_sequence` BIGINT NOT NULL COMMENT 'Column ai_runtime_operation_counters.last_sequence',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_operation_counters.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_operation_counters.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_operation_counters_namespace_digest_tenant_id_stream_digest` (`namespace_digest`, `tenant_id`, `stream_digest`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_operation_counters';

CREATE TABLE `ai_runtime_operations` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_operations.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.tenant_id',
  `runtime_domain` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.runtime_domain',
  `resource_kind` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.resource_kind',
  `resource_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.resource_id',
  `stream_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.stream_digest',
  `operation_kind` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.operation_kind',
  `operation_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.operation_id',
  `operation_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.operation_digest',
  `sequence` BIGINT NOT NULL COMMENT 'Column ai_runtime_operations.sequence',
  `stream_sequence_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.stream_sequence_digest',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.status',
  `execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_operations.execution_id',
  `request_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_operations.request_digest',
  `result_ref` TEXT COMMENT 'Column ai_runtime_operations.result_ref',
  `result_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_operations.result_digest',
  `error_code` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_operations.error_code',
  `compactable` BOOL NOT NULL COMMENT 'Column ai_runtime_operations.compactable',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_operations.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_operations.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_operations_namespace_digest_tenant_id_operation_digest` (`namespace_digest`, `tenant_id`, `operation_digest`),
  UNIQUE KEY `uk_ai_runtime_operations_stream` (`namespace_digest`, `tenant_id`, `stream_sequence_digest`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_operations';

CREATE TABLE `ai_runtime_recovery_checkpoints` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.tenant_id',
  `execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.execution_id',
  `step_run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.step_run_id',
  `agent_run_sequence` BIGINT NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.agent_run_sequence',
  `state` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.state',
  `handoff_phase` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.handoff_phase',
  `input` JSON NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.input',
  `terminal_handoff` JSON COMMENT 'Column ai_runtime_recovery_checkpoints.terminal_handoff',
  `handoff_contract_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_recovery_checkpoints.handoff_contract_digest',
  `pending_operation_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_recovery_checkpoints.pending_operation_id',
  `revision` BIGINT NOT NULL COMMENT 'Column ai_runtime_recovery_checkpoints.revision',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_recovery_checkpoints.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_recovery_checkpoints.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_recovery_checkpoints_namespace_digest_tenant_id_execution_id` (`namespace_digest`, `tenant_id`, `execution_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_recovery_checkpoints';

CREATE TABLE `ai_runtime_sessions` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_sessions.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_sessions.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_sessions.tenant_id',
  `session_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_sessions.session_id',
  `owner_principal_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_sessions.owner_principal_id',
  `binding_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_sessions.binding_digest',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_sessions.status',
  `revision` BIGINT NOT NULL COMMENT 'Column ai_runtime_sessions.revision',
  `resource_generation` BIGINT NOT NULL COMMENT 'Column ai_runtime_sessions.resource_generation',
  `cwd` TEXT COMMENT 'Column ai_runtime_sessions.cwd',
  `metadata` JSON NOT NULL COMMENT 'Column ai_runtime_sessions.metadata',
  `continuation_step_run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_sessions.continuation_step_run_id',
  `closed_at` DATETIME COMMENT 'Column ai_runtime_sessions.closed_at',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_sessions.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_sessions.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_sessions_namespace_digest_tenant_id_session_id` (`namespace_digest`, `tenant_id`, `session_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_sessions';

CREATE TABLE `ai_runtime_task_graphs` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_task_graphs.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_graphs.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_graphs.tenant_id',
  `graph_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_graphs.graph_id',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_graphs.status',
  `revision` BIGINT NOT NULL COMMENT 'Column ai_runtime_task_graphs.revision',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_task_graphs.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_task_graphs.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_task_graphs_namespace_digest_tenant_id_graph_id` (`namespace_digest`, `tenant_id`, `graph_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_task_graphs';

CREATE TABLE `ai_runtime_task_nodes` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_task_nodes.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_nodes.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_nodes.tenant_id',
  `graph_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_nodes.graph_id',
  `node_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_nodes.node_id',
  `identity_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_nodes.identity_digest',
  `dependencies` JSON NOT NULL COMMENT 'Column ai_runtime_task_nodes.dependencies',
  `input` JSON COMMENT 'Column ai_runtime_task_nodes.input',
  `budget_cost` BIGINT COMMENT 'Column ai_runtime_task_nodes.budget_cost',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_task_nodes.status',
  `revision` BIGINT NOT NULL COMMENT 'Column ai_runtime_task_nodes.revision',
  `owner` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_task_nodes.owner',
  `fence` BIGINT NOT NULL COMMENT 'Column ai_runtime_task_nodes.fence',
  `lease_expires_at` DATETIME COMMENT 'Column ai_runtime_task_nodes.lease_expires_at',
  `execution_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_task_nodes.execution_id',
  `result_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_task_nodes.result_digest',
  `error_code` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_task_nodes.error_code',
  `error_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_task_nodes.error_digest',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_task_nodes.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_task_nodes.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_task_nodes_namespace_digest_tenant_id_identity_digest` (`namespace_digest`, `tenant_id`, `identity_digest`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_task_nodes';

CREATE TABLE `ai_runtime_tool_operations` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_runtime_tool_operations.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.tenant_id',
  `tool_operation_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.tool_operation_id',
  `step_run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.step_run_id',
  `tool_call_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.tool_call_id',
  `call_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.call_digest',
  `idempotency_key_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.idempotency_key_digest',
  `tool_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.tool_name',
  `arguments_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.arguments_digest',
  `binding_fingerprint` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.binding_fingerprint',
  `replay_safe` BOOL NOT NULL COMMENT 'Column ai_runtime_tool_operations.replay_safe',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_runtime_tool_operations.status',
  `owner` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_tool_operations.owner',
  `fence` BIGINT NOT NULL COMMENT 'Column ai_runtime_tool_operations.fence',
  `lease_expires_at` DATETIME COMMENT 'Column ai_runtime_tool_operations.lease_expires_at',
  `result_store_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_tool_operations.result_store_id',
  `result_object_key` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_tool_operations.result_object_key',
  `result_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_tool_operations.result_digest',
  `result_size` BIGINT COMMENT 'Column ai_runtime_tool_operations.result_size',
  `error_code` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_runtime_tool_operations.error_code',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_tool_operations.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_runtime_tool_operations.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_tool_operations_step_call` (`namespace_digest`, `tenant_id`, `call_digest`),
  UNIQUE KEY `uk_ai_runtime_tool_operations_namespace_digest_tenant_id_tool_operation_id` (`namespace_digest`, `tenant_id`, `tool_operation_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_runtime_tool_operations';

CREATE TABLE `ai_step_effects` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_step_effects.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_effects.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_effects.tenant_id',
  `run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_effects.run_id',
  `effect_index` BIGINT NOT NULL COMMENT 'Column ai_step_effects.effect_index',
  `identity_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_effects.identity_digest',
  `tool_call_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_effects.tool_call_id',
  `tool_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_effects.tool_name',
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_effects.status',
  `started_at` DATETIME NOT NULL COMMENT 'Column ai_step_effects.started_at',
  `ended_at` DATETIME COMMENT 'Column ai_step_effects.ended_at',
  `idempotency_key` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_effects.idempotency_key',
  `effect_summary` TEXT COMMENT 'Column ai_step_effects.effect_summary',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_step_effects.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_step_effects.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_step_effects_namespace_digest_tenant_id_identity_digest` (`namespace_digest`, `tenant_id`, `identity_digest`),
  KEY `ix_ai_step_effects_tool` (`namespace_digest`, `tenant_id`, `run_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_step_effects';

CREATE TABLE `ai_step_events` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_step_events.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_events.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_events.tenant_id',
  `run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_events.run_id',
  `event_index` BIGINT NOT NULL COMMENT 'Column ai_step_events.event_index',
  `identity_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_events.identity_digest',
  `kind` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_events.kind',
  `step_index` BIGINT NOT NULL COMMENT 'Column ai_step_events.step_index',
  `timestamp` DATETIME NOT NULL COMMENT 'Column ai_step_events.timestamp',
  `conversation_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_events.conversation_id',
  `parent_run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_events.parent_run_id',
  `agent_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_events.agent_name',
  `tool_call_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_events.tool_call_id',
  `tool_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_events.tool_name',
  `error` TEXT COMMENT 'Column ai_step_events.error',
  `metadata` JSON NOT NULL COMMENT 'Column ai_step_events.metadata',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_step_events.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_step_events.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_step_events_namespace_digest_tenant_id_identity_digest` (`namespace_digest`, `tenant_id`, `identity_digest`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_step_events';

CREATE TABLE `ai_step_runs` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_step_runs.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_runs.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_runs.tenant_id',
  `runtime_domain` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_runs.runtime_domain',
  `run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_runs.run_id',
  `run_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_runs.run_digest',
  `conversation_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_runs.conversation_id',
  `parent_run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_runs.parent_run_id',
  `agent_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_runs.agent_name',
  `metadata` JSON NOT NULL COMMENT 'Column ai_step_runs.metadata',
  `last_event_index` BIGINT NOT NULL COMMENT 'Column ai_step_runs.last_event_index',
  `last_snapshot_index` BIGINT NOT NULL COMMENT 'Column ai_step_runs.last_snapshot_index',
  `last_effect_index` BIGINT NOT NULL COMMENT 'Column ai_step_runs.last_effect_index',
  `started_at` DATETIME NOT NULL COMMENT 'Column ai_step_runs.started_at',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_step_runs.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_step_runs.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_step_runs_namespace_digest_tenant_id_run_digest` (`namespace_digest`, `tenant_id`, `run_digest`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_step_runs';

CREATE TABLE `ai_step_snapshots` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_step_snapshots.id',
  `namespace_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_snapshots.namespace_digest',
  `tenant_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_snapshots.tenant_id',
  `runtime_domain` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_snapshots.runtime_domain',
  `run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_snapshots.run_id',
  `snapshot_index` BIGINT NOT NULL COMMENT 'Column ai_step_snapshots.snapshot_index',
  `identity_digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_snapshots.identity_digest',
  `step_index` BIGINT NOT NULL COMMENT 'Column ai_step_snapshots.step_index',
  `state` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_snapshots.state',
  `conversation_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_snapshots.conversation_id',
  `parent_run_id` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_snapshots.parent_run_id',
  `agent_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Column ai_step_snapshots.agent_name',
  `timestamp` DATETIME NOT NULL COMMENT 'Column ai_step_snapshots.timestamp',
  `object_store_id` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_step_snapshots.object_store_id',
  `messages` JSON NOT NULL COMMENT 'Column ai_step_snapshots.messages',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_step_snapshots.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_step_snapshots.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_step_snapshots_namespace_digest_tenant_id_identity_digest` (`namespace_digest`, `tenant_id`, `identity_digest`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_step_snapshots';

CREATE TABLE `ai_storage_object_chunks` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_storage_object_chunks.id',
  `object_id` BIGINT NOT NULL COMMENT 'Column ai_storage_object_chunks.object_id',
  `chunk_index` BIGINT NOT NULL COMMENT 'Column ai_storage_object_chunks.chunk_index',
  `content` LONGBLOB NOT NULL COMMENT 'Column ai_storage_object_chunks.content',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_storage_object_chunks.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_storage_object_chunks.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_storage_object_chunks_object_index` (`object_id`, `chunk_index`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_storage_object_chunks';

CREATE TABLE `ai_storage_objects` (
  `id` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Column ai_storage_objects.id',
  `object_key` VARCHAR(255) NOT NULL COMMENT 'Column ai_storage_objects.object_key',
  `digest` CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Column ai_storage_objects.digest',
  `size` BIGINT NOT NULL COMMENT 'Column ai_storage_objects.size',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_storage_objects.updated_at',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Column ai_storage_objects.created_at',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_storage_objects_object_key` (`object_key`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Table ai_storage_objects';
