#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Stable errors exposed at the AI package boundary."""

import hashlib
import json
from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from linktools.errors import Error


def _cause_digest(value: Mapping[str, str]) -> str:
    raw = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


class ErrorCode(StrEnum):
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    ACTIVITY_SCOPE_REQUIRED = "ACTIVITY_SCOPE_REQUIRED"
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    ASSET_CODEC_CONFLICT = "ASSET_CODEC_CONFLICT"
    ASSET_CODEC_UNKNOWN = "ASSET_CODEC_UNKNOWN"
    ASSET_LAYOUT_CONFLICT = "ASSET_LAYOUT_CONFLICT"
    ASSET_LAYOUT_UNKNOWN = "ASSET_LAYOUT_UNKNOWN"
    ASSET_CONFIG_TYPE_INVALID = "ASSET_CONFIG_TYPE_INVALID"
    ASSET_CONTENT_MISMATCH = "ASSET_CONTENT_MISMATCH"
    ASSET_CURSOR_INVALID = "ASSET_CURSOR_INVALID"
    CURSOR_INVALID = "CURSOR_INVALID"
    ASSET_ENV_MISSING = "ASSET_ENV_MISSING"
    ASSET_PATH_OUTSIDE_ROOT = "ASSET_PATH_OUTSIDE_ROOT"
    ASSET_PATH_ABSOLUTE = "ASSET_PATH_ABSOLUTE"
    ASSET_RECOVERY_REQUIRED = "ASSET_RECOVERY_REQUIRED"
    ASSET_BATCH_PARTIAL_FAILURE = "ASSET_BATCH_PARTIAL_FAILURE"
    APPROVAL_CONFLICT = "APPROVAL_CONFLICT"
    CONTEXT_PAYLOAD_TOO_LARGE = "CONTEXT_PAYLOAD_TOO_LARGE"
    EVALUATION_INCOMPATIBLE = "EVALUATION_INCOMPATIBLE"
    CAPABILITY_CONFLICT = "CAPABILITY_CONFLICT"
    CAPABILITY_FINGERPRINT_INVALID = "CAPABILITY_FINGERPRINT_INVALID"
    CAPABILITY_PROVIDER_UNKNOWN = "CAPABILITY_PROVIDER_UNKNOWN"
    CAPABILITY_REQUIRED_MISSING = "CAPABILITY_REQUIRED_MISSING"
    CAPABILITY_RESOLUTION_INVALID = "CAPABILITY_RESOLUTION_INVALID"
    CAPABILITY_POLICY_CONFLICT = "CAPABILITY_POLICY_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    OUTPUT_CONTRACT_INVALID = "OUTPUT_CONTRACT_INVALID"
    RUNTIME_DEPENDENCY_NOT_READY = "RUNTIME_DEPENDENCY_NOT_READY"
    SERVICE_NOT_READY = "SERVICE_NOT_READY"
    SESSION_BINDING_MISMATCH = "SESSION_BINDING_MISMATCH"
    SESSION_BUSY = "SESSION_BUSY"
    SESSION_CONFLICT = "SESSION_CONFLICT"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    STORAGE_BATCH_DUPLICATE_KEY = "STORAGE_BATCH_DUPLICATE_KEY"
    STORAGE_BATCH_PARTIAL_FAILURE = "STORAGE_BATCH_PARTIAL_FAILURE"
    STORAGE_CACHE_CORRUPT = "STORAGE_CACHE_CORRUPT"
    STORAGE_OWNER_MISMATCH = "STORAGE_OWNER_MISMATCH"
    STORAGE_REVISION_NOTIFY_FAILED = "STORAGE_REVISION_NOTIFY_FAILED"
    STORAGE_READ_ONLY = "STORAGE_READ_ONLY"
    STORAGE_NOT_FOUND = "STORAGE_NOT_FOUND"
    STORAGE_VERSION_UNSUPPORTED = "STORAGE_VERSION_UNSUPPORTED"
    STORAGE_CAPABILITY_MISSING = "STORAGE_CAPABILITY_MISSING"
    STORAGE_CONFLICT = "STORAGE_CONFLICT"
    STORAGE_INTEGRITY_ERROR = "STORAGE_INTEGRITY_ERROR"
    STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE"
    STORAGE_DEPENDENCY_NOT_READY = "STORAGE_DEPENDENCY_NOT_READY"
    OPTIONAL_DEPENDENCY_MISSING = "OPTIONAL_DEPENDENCY_MISSING"
    OUTPUT_SCHEMA_DRIFT = "OUTPUT_SCHEMA_DRIFT"
    OUTPUT_SCHEMA_UNKNOWN = "OUTPUT_SCHEMA_UNKNOWN"
    OUTPUT_VALIDATION_FAILED = "OUTPUT_VALIDATION_FAILED"
    BINDING_NOT_REGISTERED = "BINDING_NOT_REGISTERED"
    BINDING_CONFLICT = "BINDING_CONFLICT"
    AGENT_DEFINITION_UNAVAILABLE = "AGENT_DEFINITION_UNAVAILABLE"
    SANDBOX_UNAVAILABLE = "SANDBOX_UNAVAILABLE"
    TASK_DAG_INVALID = "TASK_DAG_INVALID"
    TASK_FENCE_STALE = "TASK_FENCE_STALE"
    TASK_OWNER_CONFLICT = "TASK_OWNER_CONFLICT"
    TASK_RESULT_CONFLICT = "TASK_RESULT_CONFLICT"
    TASK_TERMINAL_CONFLICT = "TASK_TERMINAL_CONFLICT"
    TASK_NOT_READY = "TASK_NOT_READY"
    TASK_NODE_FAILED = "TASK_NODE_FAILED"
    TASK_DEPENDENCY_FAILED = "TASK_DEPENDENCY_FAILED"
    LINKTOOLS_AI_RELEASE_MISMATCH = "LINKTOOLS_AI_RELEASE_MISMATCH"
    HTTP_ROUTE_NOT_FOUND = "HTTP_ROUTE_NOT_FOUND"
    MIDDLEWARE_FAILED = "MIDDLEWARE_FAILED"
    MODEL_REGISTRY_CONFLICT = "MODEL_REGISTRY_CONFLICT"
    MODEL_CONNECTION_NOT_FOUND = "MODEL_CONNECTION_NOT_FOUND"
    MODEL_CONNECTION_CONFLICT = "MODEL_CONNECTION_CONFLICT"
    MODEL_CONNECTION_UNSUPPORTED = "MODEL_CONNECTION_UNSUPPORTED"
    SESSION_ACTIVE_EXECUTIONS = "SESSION_ACTIVE_EXECUTIONS"
    SESSION_CLEANUP_REQUIRED = "SESSION_CLEANUP_REQUIRED"
    LOCAL_SKILL_CONFLICT = "LOCAL_SKILL_CONFLICT"
    REQUEST_FIELD_INVALID = "REQUEST_FIELD_INVALID"
    PROMPT_TOO_LARGE = "PROMPT_TOO_LARGE"
    EXTERNAL_RESULT_TOO_LARGE = "EXTERNAL_RESULT_TOO_LARGE"
    TOOL_ARGUMENTS_TOO_LARGE = "TOOL_ARGUMENTS_TOO_LARGE"
    OBSERVATION_PAYLOAD_TOO_LARGE = "OBSERVATION_PAYLOAD_TOO_LARGE"
    PAGE_LIMIT_INVALID = "PAGE_LIMIT_INVALID"
    IDEMPOTENCY_KEY_INVALID = "IDEMPOTENCY_KEY_INVALID"
    RUNTIME_SERVICE_MISMATCH = "RUNTIME_SERVICE_MISMATCH"
    STORAGE_CLOSED = "STORAGE_CLOSED"
    STORAGE_RECOVERY_REQUIRED = "STORAGE_RECOVERY_REQUIRED"
    SESSION_REVISION_CONFLICT = "SESSION_REVISION_CONFLICT"
    EXECUTION_RESULT_CONFLICT = "EXECUTION_RESULT_CONFLICT"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
    EXECUTION_START_UNKNOWN = "EXECUTION_START_UNKNOWN"
    EXECUTION_START_PERSISTENCE_FAILED = "EXECUTION_START_PERSISTENCE_FAILED"
    EXECUTION_HISTORY_UNAVAILABLE = "EXECUTION_HISTORY_UNAVAILABLE"
    EXECUTION_USAGE_LIMIT_EXCEEDED = "EXECUTION_USAGE_LIMIT_EXCEEDED"
    EXTERNAL_RESULT_CONFLICT = "EXTERNAL_RESULT_CONFLICT"
    AGENT_ID_INVALID = "AGENT_ID_INVALID"
    AGENT_INSTRUCTIONS_OUTSIDE_ROOT = "AGENT_INSTRUCTIONS_OUTSIDE_ROOT"
    TOOL_TIMEOUT_INVALID = "TOOL_TIMEOUT_INVALID"
    TOOL_OUTPUT_TRUNCATED = "TOOL_OUTPUT_TRUNCATED"
    TOOL_OPERATION_CONFLICT = "TOOL_OPERATION_CONFLICT"
    TOOL_EFFECT_UNKNOWN = "TOOL_EFFECT_UNKNOWN"
    TOOL_RESULT_CONFLICT = "TOOL_RESULT_CONFLICT"
    TOO_MANY_PENDING_OPERATIONS = "TOO_MANY_PENDING_OPERATIONS"
    TASK_GRAPH_CYCLE = "TASK_GRAPH_CYCLE"
    TASK_GRAPH_DEADLOCK = "TASK_GRAPH_DEADLOCK"
    TASK_DEPENDENCY_UNKNOWN = "TASK_DEPENDENCY_UNKNOWN"
    OUTPUT_SCHEMA_REVISION_REQUIRED = "OUTPUT_SCHEMA_REVISION_REQUIRED"
    ASSET_VERSION_NOT_FOUND = "ASSET_VERSION_NOT_FOUND"
    ASSET_VERSION_OWNER_UNKNOWN = "ASSET_VERSION_OWNER_UNKNOWN"
    REDACTION_FAILED = "REDACTION_FAILED"
    MCP_RESPONSE_TOO_LARGE = "MCP_RESPONSE_TOO_LARGE"
    LOCAL_SHELL_PLATFORM_UNSUPPORTED = "LOCAL_SHELL_PLATFORM_UNSUPPORTED"


@dataclass(frozen=True, slots=True)
class SafeError:
    code: str
    category: str
    retryable: bool
    operation_id: str
    safe_details: "Mapping[str, object]"
    cause_digest: str


class AIError(Error):
    """An error with a stable machine-readable code."""

    def __init__(
        self,
        code: ErrorCode,
        message: str = "",
        *,
        category: 'str | None' = None,
        retryable: 'bool | None' = None,
        operation_id: 'str | None' = None,
        safe_details: 'Mapping[str, object] | None' = None,
    ) -> None:
        super().__init__(message or code.value)
        self.code = code
        self.category = category or code.value.split("_", 1)[0]
        self.retryable = code in {
            ErrorCode.RUNTIME_DEPENDENCY_NOT_READY,
            ErrorCode.SERVICE_NOT_READY,
            ErrorCode.STORAGE_CACHE_CORRUPT,
            ErrorCode.STORAGE_OWNER_MISMATCH,
            ErrorCode.STORAGE_UNAVAILABLE,
            ErrorCode.STORAGE_DEPENDENCY_NOT_READY,
            ErrorCode.SESSION_ACTIVE_EXECUTIONS,
            ErrorCode.SESSION_CLEANUP_REQUIRED,
        } if retryable is None else retryable
        self.operation_id = operation_id
        self.safe_details = dict(safe_details or {})

    def to_safe_error(self, *, operation_id: str) -> SafeError:
        return SafeError(
            self.code.value,
            self.category,
            self.retryable,
            operation_id,
            self.safe_details,
            _cause_digest({"type": type(self).__name__, "code": self.code.value}),
        )


class StorageError(AIError):
    def __init__(self, message: str, code: ErrorCode = ErrorCode.STORAGE_UNAVAILABLE) -> None:
        super().__init__(code, message)


class StorageConflictError(StorageError):
    def __init__(self, message: str) -> None:
        super().__init__(message, ErrorCode.STORAGE_CONFLICT)


class StorageCorruptionError(StorageError):
    def __init__(self, message: str) -> None:
        super().__init__(message, ErrorCode.STORAGE_INTEGRITY_ERROR)


class InvalidStoragePathError(StorageError):
    def __init__(self, message: str) -> None:
        super().__init__(message, ErrorCode.STORAGE_INTEGRITY_ERROR)


class AssetError(AIError):
    def __init__(self, message: str, code: ErrorCode = ErrorCode.STORAGE_UNAVAILABLE) -> None:
        super().__init__(code, message)


class AssetConflictError(AssetError):
    def __init__(self, message: str) -> None:
        super().__init__(message, ErrorCode.STORAGE_CONFLICT)


class AssetNotFoundError(AssetError):
    def __init__(self, message: str) -> None:
        super().__init__(message, ErrorCode.STORAGE_NOT_FOUND)


class AssetParseError(AssetError):
    def __init__(self, message: str) -> None:
        super().__init__(message, ErrorCode.OUTPUT_CONTRACT_INVALID)


class InvalidAssetError(AssetError):
    def __init__(self, message: str) -> None:
        super().__init__(message, ErrorCode.OUTPUT_CONTRACT_INVALID)


__all__ = [
    "AIError",
    "AssetConflictError",
    "AssetError",
    "AssetNotFoundError",
    "AssetParseError",
    "ErrorCode",
    "InvalidAssetError",
    "InvalidStoragePathError",
    "SafeError",
    "StorageConflictError",
    "StorageCorruptionError",
    "StorageError",
]
