#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "linktools-ai/src/linktools/ai/runtime/state/_migration.py"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


text = PATH.read_text(encoding="utf-8")

anchor = '''def _collect_execution_binding(\n'''
helper = '''def _decode_current_record(\n    data: Mapping[str, JsonValue],\n    target: type[object],\n) -> object | None:\n    try:\n        return _decode_enveloped_domain(data, target)\n    except AIError as error:\n        if error.code is ErrorCode.STORAGE_INTEGRITY_ERROR:\n            return None\n        raise\n\n\n'''
if helper not in text:
    text = replace_once(text, anchor, helper + anchor, "current record helper")

old = '''def _collect_execution_binding(\n    record: StoredRecord,\n    compiler: AgentCompiler,\n    catalog: AgentCatalog,\n    bindings: dict[str, AgentBinding],\n    agents: dict[str, str],\n    targets: dict[str, tuple[str, str]],\n) -> None:\n    fields = _domain_fields(\n        record.data,\n        type_name="execution_record",\n        wire_id="execution_record",\n    )\n    if frozenset(fields) != _EXECUTION_V1_FIELDS:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n    binding = fields["binding"]\n    if _is_current_binding(binding):\n        current = _decode_enveloped_domain(record.data, ExecutionRecord)\n        _remember_execution_target(\n            targets,\n            current.execution_id,\n            current.binding_digest,\n            current.binding.output_schema_fingerprint,\n        )\n        return\n'''
new = '''def _collect_execution_binding(\n    record: StoredRecord,\n    compiler: AgentCompiler,\n    catalog: AgentCatalog,\n    bindings: dict[str, AgentBinding],\n    agents: dict[str, str],\n    targets: dict[str, tuple[str, str]],\n) -> None:\n    current = _decode_current_record(record.data, ExecutionRecord)\n    if isinstance(current, ExecutionRecord):\n        _remember_execution_target(\n            targets,\n            current.execution_id,\n            current.binding_digest,\n            current.binding.output_schema_fingerprint,\n        )\n        return\n    fields = _domain_fields(\n        record.data,\n        type_name="execution_record",\n        wire_id="execution_record",\n    )\n    if frozenset(fields) != _EXECUTION_V1_FIELDS:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n    binding = fields["binding"]\n    if _is_current_binding(binding):\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n'''
text = replace_once(text, old, new, "collect execution")

old = '''def _collect_recovery_binding(\n    record: StoredRecord,\n    compiler: AgentCompiler,\n    catalog: AgentCatalog,\n    bindings: dict[str, AgentBinding],\n    agents: dict[str, str],\n) -> None:\n    fields = _domain_fields(\n        record.data,\n        type_name="recovery_admission",\n        wire_id="recovery_admission",\n    )\n    input_fields = _nested_dataclass_fields(\n        fields.get("input"), "recovery_execution_input"\n    )\n    keys = frozenset(input_fields)\n    binding = input_fields.get("binding")\n    if keys == _CURRENT_RECOVERY_INPUT_FIELDS:\n        if not _is_current_binding(binding):\n            raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n        _decode_enveloped_domain(record.data, RecoveryAdmissionRecord)\n        return\n'''
new = '''def _collect_recovery_binding(\n    record: StoredRecord,\n    compiler: AgentCompiler,\n    catalog: AgentCatalog,\n    bindings: dict[str, AgentBinding],\n    agents: dict[str, str],\n) -> None:\n    current = _decode_current_record(record.data, RecoveryAdmissionRecord)\n    if isinstance(current, RecoveryAdmissionRecord):\n        return\n    fields = _domain_fields(\n        record.data,\n        type_name="recovery_admission",\n        wire_id="recovery_admission",\n    )\n    input_fields = _nested_dataclass_fields(\n        fields.get("input"), "recovery_execution_input"\n    )\n    keys = frozenset(input_fields)\n    binding = input_fields.get("binding")\n    if keys == _CURRENT_RECOVERY_INPUT_FIELDS:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n'''
text = replace_once(text, old, new, "collect recovery")

old = '''def _migrate_execution_data(\n    record: StoredRecord,\n    compiler: AgentCompiler,\n    catalog: AgentCatalog,\n    bindings: dict[str, AgentBinding],\n    agents: dict[str, str],\n) -> Mapping[str, JsonValue] | None:\n    fields = _domain_fields(\n        record.data,\n        type_name="execution_record",\n        wire_id="execution_record",\n    )\n    if frozenset(fields) != _EXECUTION_V1_FIELDS:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n    binding = fields["binding"]\n    if _is_current_binding(binding):\n        _decode_enveloped_domain(record.data, ExecutionRecord)\n        return None\n'''
new = '''def _migrate_execution_data(\n    record: StoredRecord,\n    compiler: AgentCompiler,\n    catalog: AgentCatalog,\n    bindings: dict[str, AgentBinding],\n    agents: dict[str, str],\n) -> Mapping[str, JsonValue] | None:\n    current = _decode_current_record(record.data, ExecutionRecord)\n    if isinstance(current, ExecutionRecord):\n        return None\n    fields = _domain_fields(\n        record.data,\n        type_name="execution_record",\n        wire_id="execution_record",\n    )\n    if frozenset(fields) != _EXECUTION_V1_FIELDS:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n    binding = fields["binding"]\n    if _is_current_binding(binding):\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n'''
text = replace_once(text, old, new, "migrate execution")

old = '''def _migrate_recovery_data(\n    record: StoredRecord,\n    compiler: AgentCompiler,\n    catalog: AgentCatalog,\n    bindings: dict[str, AgentBinding],\n    agents: dict[str, str],\n) -> Mapping[str, JsonValue] | None:\n    fields = _domain_fields(\n        record.data,\n        type_name="recovery_admission",\n        wire_id="recovery_admission",\n    )\n    input_fields = _nested_dataclass_fields(\n        fields.get("input"), "recovery_execution_input"\n    )\n    keys = frozenset(input_fields)\n    binding = input_fields.get("binding")\n    if keys == _CURRENT_RECOVERY_INPUT_FIELDS:\n        if not _is_current_binding(binding):\n            raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n        _decode_enveloped_domain(record.data, RecoveryAdmissionRecord)\n        return None\n'''
new = '''def _migrate_recovery_data(\n    record: StoredRecord,\n    compiler: AgentCompiler,\n    catalog: AgentCatalog,\n    bindings: dict[str, AgentBinding],\n    agents: dict[str, str],\n) -> Mapping[str, JsonValue] | None:\n    current = _decode_current_record(record.data, RecoveryAdmissionRecord)\n    if isinstance(current, RecoveryAdmissionRecord):\n        return None\n    fields = _domain_fields(\n        record.data,\n        type_name="recovery_admission",\n        wire_id="recovery_admission",\n    )\n    input_fields = _nested_dataclass_fields(\n        fields.get("input"), "recovery_execution_input"\n    )\n    keys = frozenset(input_fields)\n    binding = input_fields.get("binding")\n    if keys == _CURRENT_RECOVERY_INPUT_FIELDS:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n'''
text = replace_once(text, old, new, "migrate recovery")

old = '''def _migrate_session_record(\n    record: StoredRecord,\n    repository: SessionRepositoryImpl,\n    agents: Mapping[str, str],\n) -> SessionRecord | None:\n    fields = _domain_fields(\n        record.data,\n        type_name="session_record",\n        wire_id="session_record",\n    )\n    keys = frozenset(fields)\n    if keys == _CURRENT_SESSION_FIELDS:\n        _decode_enveloped_domain(record.data, SessionRecord)\n        return None\n'''
new = '''def _migrate_session_record(\n    record: StoredRecord,\n    repository: SessionRepositoryImpl,\n    agents: Mapping[str, str],\n) -> SessionRecord | None:\n    current = _decode_current_record(record.data, SessionRecord)\n    if isinstance(current, SessionRecord):\n        if current.tenant_id != repository._tenant_id:\n            raise AIError(ErrorCode.STORAGE_OWNER_MISMATCH)\n        return None\n    fields = _domain_fields(\n        record.data,\n        type_name="session_record",\n        wire_id="session_record",\n    )\n    keys = frozenset(fields)\n    if keys == _CURRENT_SESSION_FIELDS:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n'''
text = replace_once(text, old, new, "migrate session")

old = '''def _migrate_projection_data(\n    record: StoredRecord,\n    agents: Mapping[str, str],\n) -> Mapping[str, JsonValue] | None:\n    fields = _domain_fields(\n        record.data,\n        type_name="context_projection",\n        wire_id="context_projection",\n    )\n    keys = frozenset(fields)\n    if keys == _CURRENT_PROJECTION_FIELDS:\n        _decode_enveloped_domain(record.data, ContextProjection)\n        return None\n'''
new = '''def _migrate_projection_data(\n    record: StoredRecord,\n    agents: Mapping[str, str],\n) -> Mapping[str, JsonValue] | None:\n    current = _decode_current_record(record.data, ContextProjection)\n    if isinstance(current, ContextProjection):\n        return None\n    fields = _domain_fields(\n        record.data,\n        type_name="context_projection",\n        wire_id="context_projection",\n    )\n    keys = frozenset(fields)\n    if keys == _CURRENT_PROJECTION_FIELDS:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n'''
text = replace_once(text, old, new, "migrate projection")

old = '''def _persisted_dataclass_fields(\n    value: object,\n    wire_id: str,\n) -> Mapping[str, object]:\n    if not isinstance(value, Mapping):\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n    keys = set(value)\n    if keys == {"$dataclass", "fields"}:\n        pass\n    elif keys == {"$dataclass", "schema", "fields"}:\n        schema = value.get("schema")\n        if isinstance(schema, bool) or not isinstance(schema, int) or schema < 1:\n            raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n        if schema != 1:\n            raise AIError(ErrorCode.STORAGE_VERSION_UNSUPPORTED)\n    else:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n    if value.get("$dataclass") != wire_id:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n'''
new = '''def _persisted_dataclass_fields(\n    value: object,\n    wire_id: str,\n) -> Mapping[str, object]:\n    if not isinstance(value, Mapping):\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n    if set(value) != {"$dataclass", "fields"}:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n    if value.get("$dataclass") != wire_id:\n        raise AIError(ErrorCode.STORAGE_INTEGRITY_ERROR)\n'''
text = replace_once(text, old, new, "legacy parser isolation")

PATH.write_text(text, encoding="utf-8")
print("semantic migration isolated from future schema revisions")
