#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from datetime import datetime
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class CapabilityRepositoryProtocol(Protocol):
    async def upsert_file(
        self, *, kind: str, file_path: str, content: str, checksum: str, updated_by: str,
    ) -> "tuple[int, int, bool]": ...

    async def tombstone_file(
        self, kind: str, file_path: str, *, checksum: str, updated_by: str,
    ) -> bool: ...

    async def apply_batch(
        self, *, kind: str, capability_id: str, primary_rel_path: str, primary_content: str,
        supplementary_files: "list[dict[str, str | None]]", deleted_rel_paths: "list[str]",
        expected_revision: str, updated_by: str,
    ) -> "tuple[str, list[dict[str, Any]], bool]": ...

    async def list_capabilities_active(self, kind: "str | None" = None) -> "list[dict[str, Any]]": ...

    async def capability_exists(self, kind: str, capability_id: str) -> bool: ...

    async def get_file(self, kind: str, file_path: str) -> "dict[str, Any] | None": ...

    async def get_file_at_version(self, kind: str, file_path: str, version: int) -> "dict[str, Any] | None": ...

    async def get_primary_files(self, kind: str, primary_rel: str) -> "list[dict[str, Any]]": ...

    async def list_files(self, kind: str, capability_id: str) -> "list[dict[str, Any]]": ...

    async def list_file_states(self, kind: str, capability_id: str) -> "list[dict[str, Any]]": ...

    async def list_files_since(self, since: "datetime | None") -> "list[dict[str, Any]]": ...

    async def delete_files_all(self, kind: str, capability_id: str) -> int: ...

    async def restore_builtin_files(self, kind: str, capability_id: str) -> int: ...

    async def move_files(self, kind: str, old_capability_id: str, new_capability_id: str) -> int: ...

    async def was_capability_renamed(self, kind: str, old_capability_id: str, new_capability_id: str) -> bool: ...

    async def delete_file(self, kind: str, file_path: str) -> bool: ...

    async def rename_file(self, kind: str, old_file_path: str, new_file_path: str) -> "tuple[int, int] | None": ...


@runtime_checkable
class _CacheConfigProtocol(Protocol):
    enabled: bool


@runtime_checkable
class CapabilityCacheProtocol(Protocol):
    config: _CacheConfigProtocol

    async def get(self, key: str) -> "str | None": ...
    async def incr(self, key: str) -> int: ...
    async def delete(self, key: str) -> None: ...
    async def setex(self, key: str, ttl: int, value: str) -> None: ...
    async def try_acquire(self, key: str, value: str, ttl: int) -> bool: ...
    async def release_if_owner(self, key: str, value: str) -> bool: ...
