services:
  authelia:
    image: 'authelia/authelia:{{ AUTHELIA_TAG }}'
    command:
      - 'authelia'
      - '--config=/config/configuration.yml'
      - '--config=/config/configuration.acl.yml'
      - '--config=/config/configuration.2fa.yml'
      - '--config=/config/configuration.oidc.yml'
    environment:
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/storage_encryption_key
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/jwt_secret
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/secrets/oidc_hmac_secret
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS={{ AUTHELIA_LDAP_ADDRESS }}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN={{ AUTHELIA_LDAP_BASE_DN }}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER=uid={{ AUTHELIA_LDAP_USER }},ou=people,{{ AUTHELIA_LDAP_BASE_DN }}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/secrets/authentication_backend_ldap_password
      - X_AUTHELIA_CONFIG_FILTERS=template
    volumes:
      - '{{ (APP_PATH/"config") | mkdir | chown }}:/config'
      - '{{ (APP_PATH/"secrets") | mkdir | chown }}:/secrets:ro'
    networks:
      nginx:
      lldap:

  authelia-admin:
    image: 'ghcr.io/asalimonov/authelia-admin:latest'
    user: root
    volumes:
      - '{{ (APP_PATH/"config") | mkdir | chown }}:/config'
      - '{{ (APP_PATH/"secrets") | mkdir | chown }}:/secrets:ro'
    environment:
      - AAD_LOGLEVEL=DEBUG
      - AAD_AUTHELIA_DOMAIN={{ AUTHELIA_DOMAIN }}:{{ NGINX_HTTPS_PORT }}
      - AAD_AUTHELIA_COOKIE_NAME={{ manager.project_name }}-auth-session
      - AAD_AUTHELIA_MIN_AUTH_LEVEL=1
      - AAD_DIRECTORY_TYPE=lldap-graphql
      - AAD_DIRECTORY_LLDAP_GRAPHQL_ENDPOINT={{ AUTHELIA_LDAP_WEB_ADDRESS }}/api/graphql
      - AAD_DIRECTORY_LLDAP_GRAPHQL_USER={{ AUTHELIA_LDAP_USER }}
      - AAD_DIRECTORY_LLDAP_GRAPHQL_PASSWORD={{ AUTHELIA_LDAP_PASSWORD }}
      - AAD_DIRECTORY_LLDAP_GRAPHQL_LDAP_HOST={{ AUTHELIA_LDAP_HOST }}
      - AAD_DIRECTORY_LLDAP_GRAPHQL_LDAP_PORT={{ AUTHELIA_LDAP_PORT }}
      - AAD_DIRECTORY_LLDAP_GRAPHQL_LDAP_BASE_DN={{ LLDAP_BASE_DN }}
      - TRUSTED_ORIGINS={{ utils.make_url("https", AUTHELIA_DOMAIN, NGINX_HTTPS_PORT) }}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      nginx:
      lldap:
    depends_on:
     - authelia

networks:
  nginx:
  lldap:
