#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Static exports for the domain-independent storage kernel."""

from .cache import ContentCache, FilesystemContentCache, MemoryContentCache, TieredContentCache
from .composition import CacheAdapter, StorageAdapter, StorageComposition, StorageLayer
from .database import CoordinationScope, SqlSchemaManifest, SqlSchemaRegistry, SqlTableManifest, StorageDatabase, build_sqlite_storage, build_storage, close_storage, dialect_for_url
from .dialects import (
    IntegrityViolationKind,
    InsertResult,
    MySQLDialect,
    PostgreSQLDialect,
    SQLiteDialect,
    SqlAlchemyDialect,
    SqlValue,
    SqliteDialect,
    classify_integrity_error_by_message,
    primary_key_column,
    resolve_dialect,
)
from .files import Sha256Digest, StorageId, StoragePath, atomic_write_bytes, atomic_write_json, read_bytes, read_json, safe_child
from ._initialize import initialize_storage
from .layer import LayerRefreshPolicy, StorageWriteVisibility
from .model import (
    BatchStorageReader,
    BatchStorageWriter,
    MetadataChange,
    MetadataLoad,
    MetadataLoadMode,
    PreloadResult,
    ReadableMetadataBackend,
    StorageBatchFailure,
    StorageBatchPartialError,
    StorageBatchResult,
    StorageChange,
    StorageDeleteResult,
    StorageMetadataBackend,
    StorageOperation,
    StorageOwnedInfo,
    StoragePutResult,
    StorageReader,
    StorageResetResult,
    StorageWriter,
    VersionSummary,
    VersionedStorage,
)
from .names import TABLE_PREFIX, storage_name
from ._revision import BackendRevisionSource, LayerMetadataView, RevisionSource
from .lock import FileLeaseCoordinator, FileWriterLock, KeyedAsyncLock, Lease, ProcessLeaseCoordinator

__all__ = [
    "BackendRevisionSource",
    "BatchStorageReader",
    "BatchStorageWriter",
    "CacheAdapter",
    "ContentCache",
    "CoordinationScope",
    "FileLeaseCoordinator",
    "FileWriterLock",
    "FilesystemContentCache",
    "IntegrityViolationKind",
    "InsertResult",
    "KeyedAsyncLock",
    "LayerMetadataView",
    "LayerRefreshPolicy",
    "Lease",
    "MemoryContentCache",
    "MySQLDialect",
    "MetadataChange",
    "MetadataLoad",
    "MetadataLoadMode",
    "PreloadResult",
    "PostgreSQLDialect",
    "ProcessLeaseCoordinator",
    "ReadableMetadataBackend",
    "RevisionSource",
    "SqlSchemaRegistry",
    "SqlSchemaManifest",
    "SqlTableManifest",
    "StorageAdapter",
    "StorageBatchFailure",
    "StorageBatchPartialError",
    "StorageBatchResult",
    "StorageChange",
    "StorageComposition",
    "StorageDatabase",
    "StorageId",
    "StorageDeleteResult",
    "StorageLayer",
    "StoragePath",
    "StorageMetadataBackend",
    "StorageOperation",
    "StorageOwnedInfo",
    "StoragePutResult",
    "StorageReader",
    "StorageResetResult",
    "StorageWriteVisibility",
    "StorageWriter",
    "TABLE_PREFIX",
    "TieredContentCache",
    "SQLiteDialect",
    "SqlAlchemyDialect",
    "SqlValue",
    "SqliteDialect",
    "VersionSummary",
    "VersionedStorage",
    "classify_integrity_error_by_message",
    "Sha256Digest",
    "atomic_write_bytes",
    "atomic_write_json",
    "build_sqlite_storage",
    "build_storage",
    "close_storage",
    "dialect_for_url",
    "initialize_storage",
    "read_bytes",
    "read_json",
    "resolve_dialect",
    "safe_child",
    "primary_key_column",
    "storage_name",
]
