#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Static exports for the domain-independent storage kernel."""

from ._cache import ContentCache, FilesystemContentCache, InMemoryContentCache, TieredContentCache
from ._composition import CacheAdapter, StorageAdapter, StorageComposition, StorageLayer
from ._database import CoordinationScope, SqlSchemaManifest, SqlSchemaRegistry, SqlTableManifest, StorageDatabase, build_sqlite_storage, build_storage, close_storage, dialect_for_url
from ._dialects import (
    IntegrityViolationKind,
    InsertResult,
    MySQLDialect,
    PostgreSQLDialect,
    SQLiteDialect,
    SqlAlchemyDialect,
    SqlValue,
    SqliteDialect,
    classify_integrity_error_by_message,
    primary_key_column,
    resolve_dialect,
)
from ._files import Sha256Digest, StorageId, StoragePath, atomic_write_bytes, atomic_write_json, read_bytes, read_json, safe_child, write_bytes_atomic, write_json_atomic
from ._initialize import initialize_storage
from ._layer import LayerRefreshPolicy, StorageWriteVisibility
from ._contracts import (
    BatchStorageReader,
    BatchStorageWriter,
    MetadataChange,
    MetadataLoad,
    MetadataLoadMode,
    PreloadResult,
    ReadableStorageBackend,
    StorageBatchFailure,
    StorageBatchPartialError,
    StorageBatchResult,
    StorageChange,
    StorageDeleteResult,
    StorageMetadataReader,
    StorageOperation,
    StorageOwnedInfo,
    StoragePutResult,
    StorageReader,
    StorageResetResult,
    StorageWriter,
    VersionSummary,
    VersionedStorage,
)
from ._names import TABLE_PREFIX, storage_name
from ._revision import StorageRevisionSource, LayerMetadataView, RevisionSource
from ._lock import FilesystemLeaseCoordinator, FilesystemWriterLock, KeyedAsyncLock, Lease, ProcessLeaseCoordinator

__all__ = [
    "StorageRevisionSource",
    "BatchStorageReader",
    "BatchStorageWriter",
    "CacheAdapter",
    "ContentCache",
    "CoordinationScope",
    "FilesystemLeaseCoordinator",
    "FilesystemWriterLock",
    "FilesystemContentCache",
    "IntegrityViolationKind",
    "InsertResult",
    "KeyedAsyncLock",
    "LayerMetadataView",
    "LayerRefreshPolicy",
    "Lease",
    "InMemoryContentCache",
    "MySQLDialect",
    "MetadataChange",
    "MetadataLoad",
    "MetadataLoadMode",
    "PreloadResult",
    "PostgreSQLDialect",
    "ProcessLeaseCoordinator",
    "ReadableStorageBackend",
    "RevisionSource",
    "SqlSchemaRegistry",
    "SqlSchemaManifest",
    "SqlTableManifest",
    "StorageAdapter",
    "StorageBatchFailure",
    "StorageBatchPartialError",
    "StorageBatchResult",
    "StorageChange",
    "StorageComposition",
    "StorageDatabase",
    "StorageId",
    "StorageDeleteResult",
    "StorageLayer",
    "StoragePath",
    "StorageMetadataReader",
    "StorageOperation",
    "StorageOwnedInfo",
    "StoragePutResult",
    "StorageReader",
    "StorageResetResult",
    "StorageWriteVisibility",
    "StorageWriter",
    "TABLE_PREFIX",
    "TieredContentCache",
    "SQLiteDialect",
    "SqlAlchemyDialect",
    "SqlValue",
    "SqliteDialect",
    "VersionSummary",
    "VersionedStorage",
    "classify_integrity_error_by_message",
    "Sha256Digest",
    "atomic_write_bytes",
    "atomic_write_json",
    "build_sqlite_storage",
    "build_storage",
    "close_storage",
    "dialect_for_url",
    "initialize_storage",
    "read_bytes",
    "read_json",
    "resolve_dialect",
    "safe_child",
    "primary_key_column",
    "storage_name",
    "write_bytes_atomic",
    "write_json_atomic",
]
