#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Static exports for the domain-independent storage kernel."""

from ._cache import (
    ContentCache,
    FilesystemContentCache,
    InMemoryContentCache,
    TieredContentCache,
)
from ._composition import (
    CacheAdapter,
    StorageComposition,
    StorageLayer,
    StorageLocation,
    StorageValueValidator,
)
from ._contracts import (
    BatchStorageReader,
    BatchStorageWriter,
    MetadataChange,
    MetadataLoad,
    MetadataLoadMode,
    PreloadResult,
    ReadableStorageBackend,
    StorageBatchFailure,
    StorageBatchPartialError,
    StorageBatchResult,
    StorageChange,
    StorageDeleteResult,
    StorageDeletionInfo,
    StorageEntryRevision,
    StorageMetadataReader,
    StorageOperation,
    StorageOwnedInfo,
    StoragePutResult,
    StorageReader,
    StorageResetResult,
    StorageRevision,
    StorageWriter,
    VersionedStorage,
    VersionSummary,
)
from ._database import (
    CoordinationScope,
    SqlSchemaManifest,
    SqlSchemaRegistry,
    SqlTableManifest,
    StorageDatabase,
    build_sqlite_storage,
    build_storage,
)
from ._dialects import (
    InsertResult,
    IntegrityViolationKind,
    MySQLDialect,
    PostgreSQLDialect,
    SqlAlchemyDialect,
    SQLiteDialect,
    SqliteDialect,
    SqlValue,
    classify_integrity_error_by_message,
    primary_key_column,
    resolve_dialect,
)
from ._files import (
    Sha256Digest,
    StorageId,
    StoragePath,
    atomic_write_bytes,
    atomic_write_json,
    read_bytes,
    read_json,
    safe_child,
    write_bytes_atomic,
    write_json_atomic,
)
from ._initialize import initialize_storage, validate_schema
from ._layer import LayerRefreshPolicy
from ._lock import (
    FilesystemLeaseCoordinator,
    FilesystemWriterLock,
    KeyedAsyncLock,
    Lease,
    ProcessLeaseCoordinator,
)
from ._names import TABLE_PREFIX, storage_name
from ._revision import LayerMetadataView, RevisionSource, StorageRevisionSource

__all__ = [
    "TABLE_PREFIX",
    "BatchStorageReader",
    "BatchStorageWriter",
    "CacheAdapter",
    "ContentCache",
    "CoordinationScope",
    "FilesystemContentCache",
    "FilesystemLeaseCoordinator",
    "FilesystemWriterLock",
    "InMemoryContentCache",
    "InsertResult",
    "IntegrityViolationKind",
    "KeyedAsyncLock",
    "LayerMetadataView",
    "LayerRefreshPolicy",
    "Lease",
    "MetadataChange",
    "MetadataLoad",
    "MetadataLoadMode",
    "MySQLDialect",
    "PostgreSQLDialect",
    "PreloadResult",
    "ProcessLeaseCoordinator",
    "ReadableStorageBackend",
    "RevisionSource",
    "SQLiteDialect",
    "Sha256Digest",
    "SqlAlchemyDialect",
    "SqlSchemaManifest",
    "SqlSchemaRegistry",
    "SqlTableManifest",
    "SqlValue",
    "SqliteDialect",
    "StorageBatchFailure",
    "StorageBatchPartialError",
    "StorageBatchResult",
    "StorageChange",
    "StorageComposition",
    "StorageDatabase",
    "StorageDeleteResult",
    "StorageDeletionInfo",
    "StorageEntryRevision",
    "StorageId",
    "StorageLayer",
    "StorageLocation",
    "StorageMetadataReader",
    "StorageOperation",
    "StorageOwnedInfo",
    "StoragePath",
    "StoragePutResult",
    "StorageReader",
    "StorageResetResult",
    "StorageRevision",
    "StorageRevisionSource",
    "StorageValueValidator",
    "StorageWriter",
    "TieredContentCache",
    "VersionSummary",
    "VersionedStorage",
    "atomic_write_bytes",
    "atomic_write_json",
    "build_sqlite_storage",
    "build_storage",
    "classify_integrity_error_by_message",
    "initialize_storage",
    "primary_key_column",
    "read_bytes",
    "read_json",
    "resolve_dialect",
    "safe_child",
    "storage_name",
    "validate_schema",
    "write_bytes_atomic",
    "write_json_atomic",
]
