dependencies:
  - jinja2
  - pyyaml
  - dotenv
  - rsa
  - dataclasses; python_version < '3.7'
  - packaging<22; python_version < '3.8'
  - packaging; python_version >= '3.8'

dev-dependencies: []

release-dependencies:
  - linktools[cli,git]>=0.9.1

optional-dependencies: {}
