{% include "Dockerfile_ADD_USER" %}

RUN set -eux; \
    if [ "$LT_USER_UID" -ne 0 ]; then \
        echo "$LT_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers; \
        adduser "$LT_USER" sudo; \
    fi
