RUN set -ex; \
    if [ -n "$ARG_GIT_NAME" ]; then \
        git config --global user.name "$ARG_GIT_NAME"; \
    fi; \
    if [ -n "$ARG_GIT_EMAIL" ]; then \
        git config --global user.email "$ARG_GIT_EMAIL"; \
    fi; \
    if [ -n "$ARG_GIT_PULL_REBASE" ]; then \
        git config --global pull.rebase "$ARG_GIT_PULL_REBASE"; \
    fi; \
    if [ -n "$ARG_GIT_PULL_FF" ]; then \
        git config --global pull.ff "$ARG_GIT_PULL_FF"; \
    fi; \
    if [ -n "$ARG_GIT_HTTP_SSLVERIFY" ]; then \
        git config --global http.sslverify "$ARG_GIT_HTTP_SSLVERIFY"; \
    fi; \
    if [ -n "$ARG_GIT_CORE_EDITOR" ]; then \
        git config --global core.editor "$ARG_GIT_CORE_EDITOR"; \
    fi
