{% include "Dockerfile_ADD_USER" %}

RUN set -eux; \
    if [ "$ARG_USER_UID" -ne 0 ]; then \
        echo "$ARG_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers; \
        adduser "$ARG_USER" sudo; \
    fi
