services:
  nginx:
    image: '{{ container.get_service_name("nginx") }}:{{ container.cert_image_revision }}'
    build:
      context: '{{ container.get_docker_context_path() }}'
      dockerfile: '{{ container.get_docker_file_destination() }}'
#   {% if NGINX_HTTPS_ENABLE %}
      secrets:
        - cntr_acme_account
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"generated") | mkdir | chown }}:/etc/nginx/generated:ro'
      - '{{ (APP_PATH/"certs") | mkdir | chown }}:/etc/certs'
      - '{{ (APP_PATH/"acme") | mkdir | chown }}:/root/.acme.sh'
    command: ["nginx", "-p", "/etc/nginx/", "-c", "/etc/nginx/generated/current/nginx.conf", "-g", "daemon off;"]
#   {% if NGINX_HTTPS_ENABLE %}
    environment:
      NGINX_HTTPS_PORT: '{{ NGINX_HTTPS_PORT }}'
#     {% for key in container.extend_configs %}
      {{ key }}: {{ container.get_config(container.extend_configs[key]) | string | replace('$', '$$') | tojson }}
#     {% endfor %}
#   {% endif %}
    ports:
      - '{{ NGINX_HTTP_PORT }}:{{ NGINX_HTTP_PORT }}'
#     {% if NGINX_HTTPS_ENABLE %}
      - '{{ NGINX_HTTPS_PORT }}:{{ NGINX_HTTPS_PORT }}'
#     {% endif %}
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "--unix-socket", "/run/nginx-health.sock", "http://localhost/health" ]
      interval: 5s
      start_period: 1s
      start_interval: 1s
    networks:
      nginx:
#     {% if "safeline" in manager.installed_state.load_names() %}
      safeline-ce:
        ipv4_address: '{{ SAFELINE_SUBNET_PREFIX }}.253'
        aliases:
          - nginx-origin
#     {% endif %}

networks:
  nginx:

# {% if NGINX_HTTPS_ENABLE %}
secrets:
  cntr_acme_account:
    file: '{{ container.get_app_path("acme-build-account.tar") }}'
# {% endif %}
