location = /__cntr/auth {
    internal;
    auth_request off;
    if ($cntr_auth_skip_{{ site.var_name }} = 1) { return 204; }
    set $cntr_auth_endpoint_{{ site.var_name }} 1;
    proxy_intercept_errors off;
    recursive_error_pages off;
    proxy_next_upstream off;
    resolver 127.0.0.11 valid=5s;
    set $cntr_auth_target http://authelia:9091/api/authz/auth-request;
    proxy_pass $cntr_auth_target;
    {% for name, value in nginx.header_items(site, authentication=True) %}
    proxy_set_header {{ nginx.complex_value(name) }} {{ value }};
    {% endfor %}
    proxy_pass_request_body off;
    proxy_http_version 1.1;
    proxy_cache off;
    proxy_connect_timeout 240;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
}
