#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Runtime state contracts and lifecycle owner."""

from ._codec import (
    CURRENT_DATA_VERSION,
    decode_alias,
    decode_envelope,
    decode_fact,
    decode_operation,
    decode_record,
    encode_alias,
    encode_envelope,
    encode_fact,
    encode_operation,
    encode_record,
    iter_runtime_object_refs,
)
from ._commands import ConversationStateCommands, ExecutionStateCommands, RuntimeStateCommands
from ._contracts import (
    ApprovalRepository,
    ArtifactState,
    ContextProjection,
    ConversationState,
    EvaluationState,
    EventRepository,
    ExecutionEventAppend,
    ExecutionRecord,
    ExecutionRepository,
    ExecutionState,
    InlineContextBlock,
    MemoryRecord,
    MemoryState,
    RecoveryCheckpointState,
    RecoveryAdmissionRecord,
    RecoveryHandoffPhase,
    RecoveryState,
    RecoveryStateRecord,
    RuntimePayloadRef,
    SessionRecord,
    SessionRepository,
    StoredStepSnapshot,
    TaskState,
    ToolOperationAdmission,
    TranscriptChunk,
    TranscriptOrigin,
    TranscriptSpanRef,
)
from ._filesystem import FilesystemStateStorageGroup, FilesystemStateStore
from ._maintenance import RuntimeStorageMaintenance
from ._memory import MemoryStateStorageGroup, MemoryStateStore
from ._plan import (
    RuntimeDomain,
    RuntimeRetentionMode,
    RuntimeStatePlan,
    RuntimeStateRoute,
)
from ._repositories import ExecutionRepositoryImpl, SessionRepositoryImpl
from ._root import RuntimeState
from ._schema import build_runtime_sql_metadata
from ._sql import SqlStateStorageGroup, SqlStateStore
from ._steps import (
    ExecutionProjectionBatch,
    ExecutionProjectionCheckpoint,
    LegacyMaterializationResult,
    PreparedStepSnapshot,
    StateStepArchive,
)
from ._history import TranscriptRepository
from ._store import (
    FactQuery,
    Observed,
    OperationQuery,
    RecordQuery,
    RecordReplacement,
    StateGroupTransaction,
    StateStore,
    StateStorageGroup,
    StateTransaction,
    StoredAlias,
    StoredFact,
    StoredOperation,
    StoredRecord,
    alias_digest,
    operation_key,
    parent_digest,
    partition_digest,
    record_key_digest,
    scope_digest,
    sequence_key,
    sortable_id,
    sortable_timestamp,
    stream_digest,
    subject_digest,
)

__all__ = [
    "CURRENT_DATA_VERSION",
    "ApprovalRepository",
    "ArtifactState",
    "ContextProjection",
    "ConversationState",
    "ConversationStateCommands",
    "EvaluationState",
    "EventRepository",
    "ExecutionEventAppend",
    "ExecutionRecord",
    "ExecutionRepository",
    "ExecutionRepositoryImpl",
    "ExecutionProjectionBatch",
    "ExecutionProjectionCheckpoint",
    "ExecutionState",
    "ExecutionStateCommands",
    "FilesystemStateStorageGroup",
    "FactQuery",
    "FilesystemStateStore",
    "InlineContextBlock",
    "LegacyMaterializationResult",
    "PreparedStepSnapshot",
    "MemoryRecord",
    "MemoryState",
    "MemoryStateStore",
    "MemoryStateStorageGroup",
    "Observed",
    "OperationQuery",
    "RecordQuery",
    "RecordReplacement",
    "RecoveryCheckpointState",
    "RecoveryAdmissionRecord",
    "RecoveryHandoffPhase",
    "RecoveryState",
    "RecoveryStateRecord",
    "RuntimeDomain",
    "RuntimeRetentionMode",
    "RuntimeState",
    "RuntimeStatePlan",
    "RuntimeStateRoute",
    "RuntimeStateCommands",
    "RuntimeStorageMaintenance",
    "RuntimePayloadRef",
    "SessionRecord",
    "SessionRepository",
    "SessionRepositoryImpl",
    "StoredStepSnapshot",
    "SqlStateStore",
    "SqlStateStorageGroup",
    "StateStepArchive",
    "StateGroupTransaction",
    "StateStore",
    "StateStorageGroup",
    "StateTransaction",
    "StoredAlias",
    "StoredFact",
    "StoredOperation",
    "StoredRecord",
    "TaskState",
    "ToolOperationAdmission",
    "TranscriptChunk",
    "TranscriptOrigin",
    "TranscriptRepository",
    "TranscriptSpanRef",
    "alias_digest",
    "build_runtime_sql_metadata",
    "decode_alias",
    "decode_envelope",
    "decode_fact",
    "decode_operation",
    "decode_record",
    "encode_alias",
    "encode_envelope",
    "encode_fact",
    "encode_operation",
    "encode_record",
    "iter_runtime_object_refs",
    "operation_key",
    "parent_digest",
    "partition_digest",
    "record_key_digest",
    "scope_digest",
    "sequence_key",
    "sortable_id",
    "sortable_timestamp",
    "stream_digest",
    "subject_digest",
]
