"""Narrow, principal-agnostic execution storage contracts."""

from typing import Protocol

from .models import (
    JsonValue,
    NewRunTraceStep,
    Page,
    RunEvaluation,
    RunEvent,
    RunRecord,
    RunSnapshot,
    RunStatus,
    RunTraceStep,
    SessionRecord,
    SessionTurn,
)


class SessionOps(Protocol):
    async def create_session(self, *, session_id: str, user_id: str | None, tenant_id: str | None) -> SessionRecord: ...
    async def get_session(self, session_id: str) -> SessionRecord | None: ...
    async def list_session_turns(self, session_id: str, *, before_sequence: int | None = None, limit: int = 50) -> Page: ...
    async def load_session_context(self, session_id: str) -> tuple[JsonValue, ...]: ...


class RunLifecycleOps(Protocol):
    async def get_run(self, run_id: str) -> RunRecord | None: ...
    async def start_run(self, **kwargs: JsonValue) -> RunRecord: ...
    async def claim_run(self, run_id: str, *, owner: str, expected_fence: int | None = None) -> RunRecord: ...
    async def heartbeat_run(self, run_id: str, *, owner: str, fence: int) -> RunRecord: ...
    async def request_cancel(self, run_id: str, *, owner: str, fence: int) -> RunRecord: ...
    async def pause_run(self, run_id: str, *, owner: str, fence: int, snapshot: RunSnapshot, pending_approval: object | None = None) -> RunRecord: ...
    async def decide_approval(self, run_id: str, *, approval_id: str, decision: str, decided_by: str) -> RunRecord: ...
    async def complete_run(self, run_id: str, *, owner: str, fence: int, snapshot: RunSnapshot) -> RunRecord: ...
    async def fail_run(self, run_id: str, *, owner: str, fence: int, snapshot: RunSnapshot) -> RunRecord: ...
    async def acknowledge_cancel(self, run_id: str, *, owner: str, fence: int, snapshot: RunSnapshot) -> RunRecord: ...


class RunTraceOps(Protocol):
    async def append_trace_steps(self, run_id: str, *, expected_sequence: int, steps: tuple[NewRunTraceStep, ...]) -> int: ...
    async def list_trace_steps(self, run_id: str, *, after_sequence: int = 0, through_sequence: int | None = None) -> tuple[RunTraceStep, ...]: ...
    async def get_snapshot(self, run_id: str) -> RunSnapshot | None: ...


class RunEventOps(Protocol):
    async def list_run_events(self, run_id: str, *, after_sequence: int = 0, limit: int = 100) -> Page: ...


class RunEvaluationOps(Protocol):
    async def save_evaluation(self, evaluation: RunEvaluation) -> None: ...
    async def list_evaluations(self, run_id: str) -> tuple[RunEvaluation, ...]: ...


class ExecutionPort(SessionOps, RunLifecycleOps, RunTraceOps, RunEventOps, RunEvaluationOps, Protocol):
    pass


class ExecutionStore:
    def __init__(self, backend: ExecutionPort) -> None:
        self.backend = backend

    def __getattr__(self, name: str):
        return getattr(self.backend, name)
