#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Registration of the non-asset tables in the published SQL schema."""

from dataclasses import dataclass
from typing import TYPE_CHECKING

from ..core.errors import ErrorCode, LinktoolsAIError
from ..storage.database import SqlSchemaRegistry
from ..storage.names import storage_name

try:
    from sqlalchemy import (
        BigInteger,
        Boolean,
        Column,
        DateTime,
        Double,
        Index,
        Integer,
        JSON,
        LargeBinary,
        Numeric,
        String,
        Table,
        Text,
        UniqueConstraint,
    )
except ModuleNotFoundError as error:
    if error.name == "sqlalchemy":
        raise LinktoolsAIError(
            ErrorCode.OPTIONAL_DEPENDENCY_MISSING,
            "SQLAlchemy is required for SQL schema registration",
        ) from error
    raise

if TYPE_CHECKING:
    from sqlalchemy.sql.schema import Table as TableType


@dataclass(frozen=True, slots=True)
class SqlRuntimeTables:
    sessions: "TableType"
    session_turns: "TableType"
    executions: "TableType"
    execution_snapshots: "TableType"
    execution_trace_steps: "TableType"
    execution_events: "TableType"
    execution_evaluations: "TableType"
    artifacts: "TableType"
    task_plans: "TableType"
    task_executions: "TableType"
    memories: "TableType"
    execution_results: "TableType"
    runtime_idempotency: "TableType"
    approvals: "TableType"
    external_results: "TableType"
    operation_ledger: "TableType"
    runtime_blobs: "TableType"
    runtime_blob_chunks: "TableType"
    repository_records: "TableType"


class SqlRuntimeSchema:
    """Register runtime tables without performing database I/O."""

    @classmethod
    def register_schema(cls, registry: SqlSchemaRegistry) -> SqlRuntimeTables:
        json_type = JSON().with_variant(Text(), "sqlite")
        integer_id = BigInteger().with_variant(Integer, "sqlite")
        sessions = Table(
            storage_name("sessions"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("session_id", String(256), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("owner_principal_id", String(256), nullable=False),
            Column("binding_digest", String(64), nullable=False),
            Column("status", String(32), nullable=False),
            Column("revision", BigInteger, nullable=False),
            Column("resource_generation", BigInteger, nullable=False),
            Column("cwd", Text, nullable=True),
            Column("metadata_json", json_type, nullable=False),
            Column("closed_at", DateTime(timezone=True), nullable=True),
            Column("user_id", String(255), nullable=True),
            Column("next_turn_sequence", Integer, nullable=False),
            Column("latest_completed_run_id", String(255), nullable=True),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "session_id", name=storage_name("sessions_uk_tenant_session_id")),
            Index(storage_name("sessions_ix_tenant_id_user_id"), "tenant_id", "user_id"),
            Index(storage_name("sessions_ix_updated_at"), "updated_at"),
            Index(storage_name("sessions_ix_created_at"), "created_at"),
        )
        session_turns = Table(
            storage_name("session_turns"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("session_id", String(256), nullable=False),
            Column("sequence", Integer, nullable=False),
            Column("execution_id", String(256), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("input", json_type, nullable=True),
            Column("delta_messages", json_type, nullable=True),
            Column("status", String(32), nullable=False),
            Column("capture_state", String(32), nullable=False),
            Column("completed_at", DateTime(timezone=True), nullable=True),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "session_id", "sequence", name=storage_name("session_turns_uk_tenant_session_id_sequence")),
            UniqueConstraint("tenant_id", "execution_id", name=storage_name("session_turns_uk_tenant_execution_id")),
            Index(storage_name("session_turns_ix_updated_at"), "updated_at"),
            Index(storage_name("session_turns_ix_created_at"), "created_at"),
        )
        executions = Table(
            storage_name("executions"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("execution_id", String(256), nullable=False),
            Column("session_id", String(256), nullable=True),
            Column("tenant_id", String(128), nullable=False),
            Column("kind", String(40), nullable=False),
            Column("runnable_id", String(256), nullable=False),
            Column("runnable_type", String(40), nullable=False),
            Column("session_turn_sequence", Integer, nullable=True),
            Column("parent_execution_id", String(256), nullable=True),
            Column("root_execution_id", String(256), nullable=False),
            Column("status", String(40), nullable=False),
            Column("definition", json_type, nullable=False),
            Column("definition_hash", String(64), nullable=False),
            Column("data", json_type, nullable=False),
            Column("owner", String(256), nullable=True),
            Column("fence", Integer, nullable=False),
            Column("lease_expires_at", DateTime(timezone=True), nullable=True),
            Column("cancel_requested_at", DateTime(timezone=True), nullable=True),
            Column("snapshot_revision", Integer, nullable=False),
            Column("trace_sequence", Integer, nullable=False),
            Column("event_sequence", Integer, nullable=False),
            Column("profile", String(32), nullable=False),
            Column("result_ref", String(512), nullable=True),
            Column("result_digest", String(64), nullable=True),
            Column("error_code", String(128), nullable=True),
            Column("safe_error_json", json_type, nullable=False),
            Column("user_id", String(255), nullable=True),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "execution_id", name=storage_name("executions_uk_tenant_execution_id")),
            Index(storage_name("executions_ix_session_id"), "session_id"),
            Index(storage_name("executions_ix_root_execution_id"), "root_execution_id"),
            Index(storage_name("executions_ix_lease_expires_at"), "lease_expires_at"),
            Index(storage_name("executions_ix_updated_at"), "updated_at"),
            Index(storage_name("executions_ix_created_at"), "created_at"),
        )
        execution_snapshots = Table(
            storage_name("execution_snapshots"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("execution_id", String(256), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("revision", Integer, nullable=False),
            Column("resume_messages", json_type, nullable=False),
            Column("outcome", json_type, nullable=False),
            Column("status", String(32), nullable=False),
            Column("trace_end_sequence", Integer, nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "execution_id", "revision", name=storage_name("execution_snapshots_uk_tenant_execution_revision")),
            Index(storage_name("execution_snapshots_ix_updated_at"), "updated_at"),
            Index(storage_name("execution_snapshots_ix_created_at"), "created_at"),
        )
        execution_trace_steps = Table(
            storage_name("execution_trace_steps"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("execution_id", String(256), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("sequence", Integer, nullable=False),
            Column("kind", String(40), nullable=False),
            Column("payload", json_type, nullable=False),
            Column("payload_digest", String(64), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "execution_id", "sequence", name=storage_name("execution_trace_steps_uk_tenant_execution_id_sequence")),
            Index(storage_name("execution_trace_steps_ix_updated_at"), "updated_at"),
            Index(storage_name("execution_trace_steps_ix_created_at"), "created_at"),
        )
        execution_events = Table(
            storage_name("execution_events"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("execution_id", String(256), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("sequence", Integer, nullable=False),
            Column("type", String(120), nullable=False),
            Column("payload", json_type, nullable=False),
            Column("payload_digest", String(64), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "execution_id", "sequence", name=storage_name("execution_events_uk_tenant_execution_id_sequence")),
            Index(storage_name("execution_events_ix_updated_at"), "updated_at"),
            Index(storage_name("execution_events_ix_created_at"), "created_at"),
        )
        execution_evaluations = Table(
            storage_name("execution_evaluations"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("evaluation_id", String(256), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("execution_id", String(256), nullable=False),
            Column("dataset_id", String(256), nullable=False),
            Column("dataset_revision", BigInteger, nullable=False),
            Column("evaluator", String(255), nullable=False),
            Column("evaluator_revision", BigInteger, nullable=False),
            Column("binding_digest", String(64), nullable=False),
            Column("output_schema_fingerprint", String(64), nullable=False),
            Column("artifact_digest", String(64), nullable=True),
            Column("status", String(32), nullable=False),
            Column("revision", BigInteger, nullable=False),
            Column("score", Double, nullable=True),
            Column("result", json_type, nullable=False),
            Column("metrics_json", json_type, nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "evaluation_id", name=storage_name("execution_evaluations_uk_tenant_evaluation_id")),
            Index(storage_name("execution_evaluations_ix_evaluator"), "evaluator"),
            Index(storage_name("execution_evaluations_ix_execution_id_created_at"), "execution_id", "created_at"),
            Index(storage_name("execution_evaluations_ix_updated_at"), "updated_at"),
            Index(storage_name("execution_evaluations_ix_created_at"), "created_at"),
        )
        artifacts = Table(
            storage_name("artifacts"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("artifact_id", String(256), nullable=False),
            Column("sha256", String(64), nullable=False),
            Column("media_type", String(128), nullable=False),
            Column("size", Integer, nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("execution_id", String(256), nullable=False),
            Column("producer_kind", String(64), nullable=False),
            Column("producer_id", String(128), nullable=False),
            Column("producer", String(256), nullable=False),
            Column("digest", String(64), nullable=False),
            Column("blob_ref", String(512), nullable=False),
            Column("run_id", String(128), nullable=True),
            Column("session_id", String(128), nullable=True),
            Column("parent_artifact_ids", json_type, nullable=False),
            Column("provenance_metadata", json_type, nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "artifact_id", name=storage_name("artifacts_uk_tenant_id_artifact_id")),
            Index(storage_name("artifacts_ix_artifact_id"), "artifact_id"),
            Index(storage_name("artifacts_ix_sha256"), "sha256"),
            Index(storage_name("artifacts_ix_updated_at"), "updated_at"),
            Index(storage_name("artifacts_ix_created_at"), "created_at"),
        )
        task_plans = Table(
            storage_name("task_plans"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("plan_id", String(256), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("graph_id", String(256), nullable=False),
            Column("status", String(32), nullable=False),
            Column("limits_json", json_type, nullable=False),
            Column("graph_digest", String(64), nullable=False),
            Column("spent_budget", BigInteger, nullable=False),
            Column("revision", BigInteger, nullable=False),
            Column("payload", json_type, nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "plan_id", name=storage_name("task_plans_uk_tenant_plan_id")),
            Index(storage_name("task_plans_ix_updated_at"), "updated_at"),
            Index(storage_name("task_plans_ix_created_at"), "created_at"),
        )
        task_executions = Table(
            storage_name("task_executions"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("execution_id", String(255), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("plan_id", String(255), nullable=False),
            Column("graph_id", String(256), nullable=False),
            Column("node_id", String(256), nullable=False),
            Column("dependencies_json", json_type, nullable=False),
            Column("binding_digest", String(64), nullable=False),
            Column("budget_cost", BigInteger, nullable=False),
            Column("status", String(32), nullable=False),
            Column("owner", String(255), nullable=True),
            Column("fence", Integer, nullable=False),
            Column("attempt", Integer, nullable=False),
            Column("result", json_type, nullable=True),
            Column("result_digest", String(64), nullable=True),
            Column("error", json_type, nullable=True),
            Column("error_code", String(128), nullable=True),
            Column("error_digest", String(64), nullable=True),
            Column("lease_expires_at", DateTime(timezone=True), nullable=True),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "execution_id", name=storage_name("task_executions_uk_tenant_execution_id")),
            Index(storage_name("task_executions_ix_plan_id"), "plan_id"),
            Index(storage_name("task_executions_ix_updated_at"), "updated_at"),
            Index(storage_name("task_executions_ix_created_at"), "created_at"),
        )
        memories = Table(
            storage_name("memories"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("memory_id", String(256), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("owner_id", String(256), nullable=False),
            Column("content", Text, nullable=False),
            Column("category", String(64), nullable=True),
            Column("confidence", Numeric(5, 4), nullable=True),
            Column("version", Integer, nullable=False),
            Column("metadata_json", Text, nullable=False),
            Column("user_id", String(128), nullable=True),
            Column("workspace_id", String(128), nullable=True),
            Column("session_id", String(128), nullable=True),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "memory_id", name=storage_name("memories_uk_tenant_memory_id")),
            Index(storage_name("memories_ix_tenant_id"), "tenant_id"),
            Index(storage_name("memories_ix_updated_at"), "updated_at"),
            Index(storage_name("memories_ix_created_at"), "created_at"),
        )
        execution_results = Table(
            storage_name("execution_results"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("tenant_id", String(128), nullable=False),
            Column("execution_id", String(256), nullable=False),
            Column("status", String(32), nullable=False),
            Column("output_schema_id", String(256), nullable=False),
            Column("output_schema_revision", BigInteger, nullable=False),
            Column("output_schema_fingerprint", String(64), nullable=False),
            Column("payload_ref", String(512), nullable=True),
            Column("payload_digest", String(64), nullable=True),
            Column("stop_reason", String(64), nullable=False),
            Column("input_tokens", BigInteger, nullable=False),
            Column("output_tokens", BigInteger, nullable=False),
            Column("total_cost_micros", BigInteger, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "execution_id", name=storage_name("execution_results_uk_tenant_execution")),
            Index(storage_name("execution_results_ix_tenant_status"), "tenant_id", "status", "created_at"),
        )
        runtime_idempotency = Table(
            storage_name("runtime_idempotency"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("scope", String(512), nullable=False),
            Column("key_hash", String(64), nullable=False),
            Column("request_digest", String(64), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("execution_id", String(256), nullable=False),
            Column("status", String(32), nullable=False),
            Column("result_digest", String(64), nullable=True),
            Column("error_code", String(128), nullable=True),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "scope", "key_hash", name=storage_name("runtime_idempotency_uk_tenant_scope_key")),
            Index(storage_name("runtime_idempotency_ix_tenant_execution"), "tenant_id", "execution_id"),
            Index(storage_name("runtime_idempotency_ix_status_updated_at"), "status", "updated_at"),
        )
        approvals = Table(
            storage_name("approvals"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("tenant_id", String(128), nullable=False),
            Column("approval_id", String(256), nullable=False),
            Column("execution_id", String(256), nullable=False),
            Column("operation_id", String(256), nullable=False),
            Column("status", String(32), nullable=False),
            Column("decision_id", String(256), nullable=True),
            Column("decision", String(16), nullable=True),
            Column("decided_by", String(256), nullable=True),
            Column("decision_digest", String(64), nullable=True),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("decided_at", DateTime(timezone=True), nullable=True),
            UniqueConstraint("tenant_id", "approval_id", name=storage_name("approvals_uk_tenant_approval")),
            UniqueConstraint("tenant_id", "approval_id", "decision_id", name=storage_name("approvals_uk_tenant_approval_decision")),
            Index(storage_name("approvals_ix_tenant_execution_status"), "tenant_id", "execution_id", "status"),
        )
        external_results = Table(
            storage_name("external_results"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("tenant_id", String(128), nullable=False),
            Column("call_id", String(256), nullable=False),
            Column("execution_id", String(256), nullable=False),
            Column("operation_id", String(256), nullable=False),
            Column("status", String(32), nullable=False),
            Column("result_id", String(256), nullable=True),
            Column("payload_ref", String(512), nullable=True),
            Column("payload_digest", String(64), nullable=True),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("supplied_at", DateTime(timezone=True), nullable=True),
            UniqueConstraint("tenant_id", "call_id", name=storage_name("external_results_uk_tenant_call")),
            UniqueConstraint("tenant_id", "call_id", "result_id", name=storage_name("external_results_uk_tenant_call_result")),
            Index(storage_name("external_results_ix_tenant_execution_status"), "tenant_id", "execution_id", "status"),
        )
        operation_ledger = Table(
            storage_name("operation_ledger"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("tenant_id", String(128), nullable=False),
            Column("operation_id", String(256), nullable=False),
            Column("resource_kind", String(64), nullable=False),
            Column("resource_id", String(256), nullable=False),
            Column("execution_id", String(256), nullable=True),
            Column("sequence", BigInteger, nullable=False),
            Column("kind", String(64), nullable=False),
            Column("status", String(32), nullable=False),
            Column("request_digest", String(64), nullable=False),
            Column("result_ref", String(512), nullable=True),
            Column("result_digest", String(64), nullable=True),
            Column("error_code", String(128), nullable=True),
            Column("compactable", Boolean, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("tenant_id", "operation_id", name=storage_name("operation_ledger_uk_tenant_operation")),
            UniqueConstraint("tenant_id", "resource_kind", "resource_id", "sequence", name=storage_name("operation_ledger_uk_tenant_resource_sequence")),
            Index(storage_name("operation_ledger_ix_tenant_resource_status"), "tenant_id", "resource_kind", "resource_id", "status", "sequence"),
            Index(storage_name("operation_ledger_ix_tenant_execution"), "tenant_id", "execution_id"),
        )
        runtime_blobs = Table(
            storage_name("runtime_blobs"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("tenant_id", String(128), nullable=False),
            Column("digest", String(64), nullable=False),
            Column("size", BigInteger, nullable=False),
            Column("status", String(32), nullable=False),
            Column("chunk_count", BigInteger, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("completed_at", DateTime(timezone=True), nullable=True),
            UniqueConstraint("tenant_id", "digest", name=storage_name("runtime_blobs_uk_tenant_digest")),
            Index(storage_name("runtime_blobs_ix_tenant_status_created_at"), "tenant_id", "status", "created_at"),
        )
        runtime_blob_chunks = Table(
            storage_name("runtime_blob_chunks"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("tenant_id", String(128), nullable=False),
            Column("digest", String(64), nullable=False),
            Column("chunk_index", BigInteger, nullable=False),
            Column("content", LargeBinary, nullable=False),
            Column("content_size", BigInteger, nullable=False),
            Column("content_digest", String(64), nullable=False),
            UniqueConstraint("tenant_id", "digest", "chunk_index", name=storage_name("runtime_blob_chunks_uk_tenant_digest_index")),
        )
        repository_records = Table(
            storage_name("runtime_repository_records"),
            registry.metadata,
            Column("id", integer_id, primary_key=True, autoincrement=True),
            Column("namespace", String(512), nullable=False),
            Column("component", String(128), nullable=False),
            Column("record_key", String(512), nullable=False),
            Column("tenant_id", String(128), nullable=False),
            Column("payload", Text, nullable=False),
            UniqueConstraint("namespace", "component", "record_key", name=storage_name("runtime_repository_records_uk_identity")),
            Index(storage_name("runtime_repository_records_ix_tenant"), "namespace", "tenant_id", "component"),
        )
        tables = (
            (sessions, "adapter.session"),
            (session_turns, "adapter.session"),
            (executions, "adapter.execution"),
            (execution_snapshots, "adapter.execution"),
            (execution_trace_steps, "adapter.execution"),
            (execution_events, "adapter.execution"),
            (execution_evaluations, "adapter.evaluation"),
            (artifacts, "adapter.artifact"),
            (task_plans, "adapter.task"),
            (task_executions, "adapter.task"),
            (memories, "adapter.memory"),
            (execution_results, "adapter.result"),
            (runtime_idempotency, "adapter.idempotency"),
            (approvals, "adapter.approval"),
            (external_results, "adapter.external"),
            (operation_ledger, "adapter.operation"),
            (runtime_blobs, "adapter.blob"),
            (runtime_blob_chunks, "adapter.blob"),
            (repository_records, "adapter.runtime"),
        )
        for table, owner in tables:
            registry.add_table(table, owner=owner)
        return SqlRuntimeTables(
            sessions,
            session_turns,
            executions,
            execution_snapshots,
            execution_trace_steps,
            execution_events,
            execution_evaluations,
            artifacts,
            task_plans,
            task_executions,
            memories,
            execution_results,
            runtime_idempotency,
            approvals,
            external_results,
            operation_ledger,
            runtime_blobs,
            runtime_blob_chunks,
            repository_records,
        )


__all__ = ["SqlRuntimeSchema", "SqlRuntimeTables"]
