#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Blob metadata and object protocols."""

from typing import Protocol


class BlobRepository(Protocol):
    async def create_staging(self, blob: object) -> object: ...
    async def commit(self, blob_id: str) -> object: ...
    async def add_reference(self, reference: object) -> object: ...
    async def delete_reference(self, reference_id: str) -> object: ...
    async def acquire_delete_lease(self, blob_id: str) -> object: ...
    async def complete_delete(self, blob_id: str, lease_id: str) -> object: ...


class ObjectStore(Protocol):
    async def put(self, key: str, content: bytes) -> object: ...
    async def get(self, key: str) -> bytes: ...
    async def head(self, key: str) -> object: ...
    async def delete(self, key: str) -> None: ...


__all__ = ["BlobRepository", "ObjectStore"]
