#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Narrow Runtime protocol composition."""

from typing import Protocol


class ExecutionApi(Protocol):
    async def run(self, request: object) -> object: ...
    async def inspect(self, execution_id: str) -> object: ...
    async def result(self, execution_id: str) -> object: ...
    async def cancel(self, execution_id: str, request: object) -> object: ...
    async def retry(self, execution_id: str, request: object) -> object: ...
    async def fork(self, execution_id: str, request: object) -> object: ...


class SessionApi(Protocol):
    async def create(self, request: object) -> object: ...
    async def get(self, session_id: str) -> object: ...
    async def list(self, request: object) -> object: ...
    async def load(self, session_id: str, request: object) -> object: ...
    async def resume(self, session_id: str, request: object) -> object: ...
    async def fork(self, session_id: str, request: object) -> object: ...
    async def update(self, session_id: str, request: object) -> object: ...
    async def close(self, session_id: str, request: object) -> object: ...


class TaskApi(Protocol):
    async def submit(self, request: object) -> object: ...
    async def inspect_task(self, task_id: str) -> object: ...
    async def list_tasks(self, request: object) -> object: ...
    async def retry_task(self, task_id: str, request: object) -> object: ...
    async def cancel_task(self, task_id: str, request: object) -> object: ...


class EvaluationApi(Protocol):
    async def run_evaluation(self, request: object) -> object: ...
    async def inspect_evaluation(self, evaluation_id: str) -> object: ...
    async def compare_evaluation(self, request: object) -> object: ...
    async def snapshot(self, evaluation_id: str) -> object: ...
    async def replay(self, snapshot_id: str, request: object) -> object: ...


class Runtime(ExecutionApi, SessionApi, TaskApi, EvaluationApi, Protocol):
    """Public runtime composition; implementations are facades."""


__all__ = ["EvaluationApi", "ExecutionApi", "Runtime", "SessionApi", "TaskApi"]
