#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Session persistence, resources and lease protocols."""

from typing import Protocol

from ..domain.session import SessionLease


class SessionRepository(Protocol):
    async def create(self, session: object) -> object: ...
    async def get(self, session_id: str) -> "object | None": ...
    async def list(self, owner_id: str, limit: int, cursor: "str | None" = None) -> object: ...
    async def compare_and_set(self, session_id: str, expected_revision: int, session: object) -> object: ...


class SessionResourcePort(Protocol):
    async def prepare(self, session: object) -> object: ...
    async def swap(self, session: object, prepared: object) -> object: ...
    async def release(self, session: object) -> object: ...
    async def reconcile(self, session: object) -> object: ...


class SessionLeasePort(Protocol):
    async def claim(self, session_id: str, owner: str, operation_id: str) -> SessionLease: ...
    async def renew(self, session_id: str, owner: str, fence: int) -> SessionLease: ...
    async def release(self, session_id: str, owner: str, fence: int) -> SessionLease: ...


class ACPSessionStore(Protocol):
    async def save(self, session: object) -> None: ...
    async def load(self, session_id: str) -> "object | None": ...
    async def delete(self, session_id: str) -> None: ...


__all__ = ["ACPSessionStore", "SessionLeasePort", "SessionRepository", "SessionResourcePort"]
