#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Task persistence and fencing protocol."""

from typing import Protocol


class TaskRepository(Protocol):
    async def submit(self, task: object) -> object: ...
    async def claim(self, task_id: str, owner: str, now: object, duration: object) -> "object | None": ...
    async def renew(self, task_id: str, owner: str, fence: int, now: object, duration: object) -> object: ...
    async def complete(self, task_id: str, owner: str, fence: int, now: object, result: object) -> object: ...
    async def fail(self, task_id: str, owner: str, fence: int, now: object, error: str) -> object: ...
    async def retry(self, task_id: str) -> object: ...


class TaskQueryRepository(Protocol):
    async def get(self, task_id: str) -> "object | None": ...
    async def list(self, job_id: "str | None", limit: int, cursor: "str | None") -> object: ...
    async def cancel(self, task_id: str, reason: str) -> object: ...


__all__ = ["TaskQueryRepository", "TaskRepository"]
